use std::collections::HashMap;

use super::model::{SensorStateSpec, SnmpDeviceProfile, SnmpProfileSensor};

/// Catálogo de perfis nativos conhecidos pelo NetMonitor.
#[must_use]
pub fn builtin_profiles() -> Vec<SnmpDeviceProfile> {
    vec![volt_mppt_solar_profile()]
}

fn state(label: &str, color: &str, icon: &str) -> SensorStateSpec {
    SensorStateSpec {
        label: label.to_string(),
        color: Some(color.to_string()),
        icon: Some(icon.to_string()),
    }
}

/// Perfil do Controlador de Carga Solar MPPT da Volt Tecnologia (12V/24V/48V - 30A).
/// Mapeamento testado e validado contra hardware real na rede local.
#[must_use]
pub fn volt_mppt_solar_profile() -> SnmpDeviceProfile {
    SnmpDeviceProfile {
        id: "volt_mppt_solar".into(),
        name: "Volt MPPT - Controlador de Carga Solar".into(),
        vendor: "Volt Tecnologia".into(),
        category: "solar_mppt".into(),
        sys_object_id_prefix: Some("1.3.6.1.4.1.17095.1".into()),
        sys_descr_pattern: Some("(?i)MPPT".into()),
        is_builtin: true,
        sensors: vec![
            SnmpProfileSensor {
                key: "pv_voltage".into(),
                label: "Tensão Painel Solar".into(),
                oid: "1.3.6.1.4.1.17095.1.3.4.0".into(),
                unit: "V".into(),
                scale: 0.1,
                category: "solar".into(),
                data_type: "float".into(),
                description: Some("Tensão de entrada dos módulos fotovoltaicos (PV)".into()),
                icon: Some("mdi-solar-power".into()),
                color: Some("amber".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "pv_current".into(),
                label: "Corrente Painel Solar".into(),
                oid: "1.3.6.1.4.1.17095.1.3.5.0".into(),
                unit: "A".into(),
                scale: 0.1,
                category: "solar".into(),
                data_type: "float".into(),
                description: Some("Corrente gerada pelos módulos fotovoltaicos".into()),
                icon: Some("mdi-current-dc".into()),
                color: Some("orange".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "pv_power".into(),
                label: "Potência Painel Solar".into(),
                oid: "1.3.6.1.4.1.17095.1.3.6.0".into(),
                unit: "W".into(),
                scale: 0.1,
                category: "solar".into(),
                data_type: "float".into(),
                description: Some("Potência instantânea gerada pelo arranjo solar".into()),
                icon: Some("mdi-flash".into()),
                color: Some("yellow-darken-2".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "energy_generated".into(),
                label: "Energia Solar Acumulada".into(),
                oid: "1.3.6.1.4.1.17095.1.3.7.0".into(),
                unit: "kWh".into(),
                scale: 0.001,
                category: "solar".into(),
                data_type: "float".into(),
                description: Some(
                    "Total acumulado de energia gerada pelos módulos fotovoltaicos".into(),
                ),
                icon: Some("mdi-counter".into()),
                color: Some("purple".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "battery_voltage".into(),
                label: "Tensão da Bateria".into(),
                oid: "1.3.6.1.4.1.17095.1.3.8.0".into(),
                unit: "V".into(),
                scale: 0.1,
                category: "battery".into(),
                data_type: "float".into(),
                description: Some("Tensão do banco de baterias (12V/24V/36V/48V)".into()),
                icon: Some("mdi-battery-charging".into()),
                color: Some("blue".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "battery_current".into(),
                label: "Corrente da Bateria".into(),
                oid: "1.3.6.1.4.1.17095.1.3.9.0".into(),
                unit: "A".into(),
                scale: 0.1,
                category: "battery".into(),
                data_type: "float".into(),
                description: Some("Corrente de carga direcionada às baterias".into()),
                icon: Some("mdi-battery-arrow-up".into()),
                color: Some("blue-grey".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "battery_status".into(),
                label: "Status da Bateria".into(),
                oid: "1.3.6.1.4.1.17095.1.3.10.0".into(),
                unit: "".into(),
                scale: 1.0,
                category: "battery".into(),
                data_type: "state".into(),
                description: Some("Estado operacional do banco de baterias (0: Descarregando, 1: Carregando, 2: Flutuação, 3: Descarregada)".into()),
                icon: Some("mdi-battery-check".into()),
                color: Some("teal".into()),
                states: Some(HashMap::from([
                    ("0".into(), state("Descarregando", "warning", "mdi-battery-arrow-down")),
                    ("1".into(), state("Carregando", "success", "mdi-battery-charging")),
                    ("2".into(), state("Carregada (Flutuação)", "info", "mdi-battery-check")),
                    ("3".into(), state("Descarregada", "error", "mdi-battery-alert")),
                ])),
            },
            SnmpProfileSensor {
                key: "load_voltage".into(),
                label: "Tensão de Saída (Carga)".into(),
                oid: "1.3.6.1.4.1.17095.1.3.11.0".into(),
                unit: "V".into(),
                scale: 0.1,
                category: "load".into(),
                data_type: "float".into(),
                description: Some("Tensão entregue aos equipamentos na saída de carga".into()),
                icon: Some("mdi-power-plug".into()),
                color: Some("cyan-darken-2".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "load_current".into(),
                label: "Corrente de Saída (Carga)".into(),
                oid: "1.3.6.1.4.1.17095.1.3.12.0".into(),
                unit: "A".into(),
                scale: 0.1,
                category: "load".into(),
                data_type: "float".into(),
                description: Some("Corrente consumida pela carga conectada".into()),
                icon: Some("mdi-power-plug-outline".into()),
                color: Some("teal".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "load_status".into(),
                label: "Status da Saída".into(),
                oid: "1.3.6.1.4.1.17095.1.3.13.0".into(),
                unit: "".into(),
                scale: 1.0,
                category: "load".into(),
                data_type: "boolean".into(),
                description: Some("Estado da saída controlada de carga (ligada/desligada)".into()),
                icon: Some("mdi-power".into()),
                color: Some("indigo".into()),
                states: Some(HashMap::from([
                    ("0".into(), state("Desligada", "grey", "mdi-power-off")),
                    ("1".into(), state("Ligada", "success", "mdi-power")),
                ])),
            },
            SnmpProfileSensor {
                key: "relay_status".into(),
                label: "Status do Relé Multifunção".into(),
                oid: "1.3.6.1.4.1.17095.1.3.14.0".into(),
                unit: "".into(),
                scale: 1.0,
                category: "load".into(),
                data_type: "boolean".into(),
                description: Some("Estado da saída de relé multifunção para backup/gerador".into()),
                icon: Some("mdi-toggle-switch".into()),
                color: Some("deep-purple".into()),
                states: Some(HashMap::from([
                    ("0".into(), state("Contato NF (Fechado)", "grey", "mdi-toggle-switch-off")),
                    ("1".into(), state("Contato NA (Aberto)", "warning", "mdi-toggle-switch")),
                ])),
            },
            SnmpProfileSensor {
                key: "internal_temp".into(),
                label: "Temperatura Interna".into(),
                oid: "1.3.6.1.4.1.17095.1.3.1.0".into(),
                unit: "°C".into(),
                scale: 1.0,
                category: "environment".into(),
                data_type: "float".into(),
                description: Some("Temperatura interna medida no dissipador do MPPT".into()),
                icon: Some("mdi-thermometer".into()),
                color: Some("deep-orange".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "external_temp".into(),
                label: "Temperatura Externa".into(),
                oid: "1.3.6.1.4.1.17095.1.3.2.0".into(),
                unit: "°C".into(),
                scale: 1.0,
                category: "environment".into(),
                data_type: "float".into(),
                description: Some("Temperatura do sensor externo de baterias".into()),
                icon: Some("mdi-thermometer-lines".into()),
                color: Some("light-blue-darken-1".into()),
                states: None,
            },
            SnmpProfileSensor {
                key: "charge_status".into(),
                label: "Modo de Operação".into(),
                oid: "1.3.6.1.4.1.17095.1.3.3.0".into(),
                unit: "".into(),
                scale: 1.0,
                category: "status".into(),
                data_type: "state".into(),
                description: Some(
                    "Modo de operação do controlador (0: Standby, 1: Painel Solar, 2: Painel + Bateria, 3: Bateria, 4: Curto-Circuito, 5: Sobrecarga, 6: Sobre Temperatura)".into(),
                ),
                icon: Some("mdi-state-machine".into()),
                color: Some("purple".into()),
                states: Some(HashMap::from([
                    ("0".into(), state("Standby", "grey", "mdi-pause-circle")),
                    ("1".into(), state("Painel Solar", "success", "mdi-solar-power")),
                    ("2".into(), state("Painel + Bateria", "info", "mdi-solar-power-variant")),
                    ("3".into(), state("Bateria", "warning", "mdi-battery-arrow-down")),
                    ("4".into(), state("Curto-Circuito", "error", "mdi-alert-octagon")),
                    ("5".into(), state("Sobrecarga", "error", "mdi-flash-alert")),
                    ("6".into(), state("Sobre Temperatura", "error", "mdi-thermometer-alert")),
                ])),
            },
        ],
    }
}
