//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "devices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub site_id: Option<i64>,
    #[sea_orm(unique_key = "devices_network_ip_unique")]
    pub network_id: Option<i64>,
    pub parent_id: Option<i64>,
    pub zabbix_template_id: Option<i64>,
    #[sea_orm(unique_key = "devices_network_ip_unique")]
    pub ip_address: Option<String>,
    pub name: String,
    pub r#type: String,
    pub vendor: Option<String>,
    pub model: Option<String>,
    pub serial_number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_monitored: bool,
    pub snmp_enabled: bool,
    pub snmp_community: Option<String>,
    pub snmp_version: Option<String>,
    pub status: String,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alert_events::Entity")]
    AlertEvents,
    #[sea_orm(has_many = "super::alert_rules::Entity")]
    AlertRules,
    #[sea_orm(has_many = "super::device_interfaces::Entity")]
    DeviceInterfaces,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::metrics::Entity")]
    Metrics,
    #[sea_orm(has_many = "super::monitors::Entity")]
    Monitors,
    #[sea_orm(
        belongs_to = "super::networks::Entity",
        from = "Column::NetworkId",
        to = "super::networks::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Networks,
    #[sea_orm(
        belongs_to = "super::sites::Entity",
        from = "Column::SiteId",
        to = "super::sites::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sites,
    #[sea_orm(has_one = "super::vpn_peers::Entity")]
    VpnPeers,
    #[sea_orm(
        belongs_to = "super::zabbix_templates::Entity",
        from = "Column::ZabbixTemplateId",
        to = "super::zabbix_templates::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    ZabbixTemplates,
}

impl Related<super::alert_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertEvents.def()
    }
}

impl Related<super::alert_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertRules.def()
    }
}

impl Related<super::device_interfaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceInterfaces.def()
    }
}

impl Related<super::metrics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Metrics.def()
    }
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}

impl Related<super::networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networks.def()
    }
}

impl Related<super::sites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sites.def()
    }
}

impl Related<super::vpn_peers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VpnPeers.def()
    }
}

impl Related<super::zabbix_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZabbixTemplates.def()
    }
}
