//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "discovery_runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub network_id: i64,
    pub probe_id: Option<i64>,
    pub status: String,
    pub started_at: DateTimeWithTimeZone,
    pub finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub configuration: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discovery_results::Entity")]
    DiscoveryResults,
    #[sea_orm(
        belongs_to = "super::networks::Entity",
        from = "Column::NetworkId",
        to = "super::networks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Networks,
    #[sea_orm(
        belongs_to = "super::probes::Entity",
        from = "Column::ProbeId",
        to = "super::probes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Probes,
}

impl Related<super::discovery_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscoveryResults.def()
    }
}

impl Related<super::networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networks.def()
    }
}

impl Related<super::probes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Probes.def()
    }
}
