//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "monitors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub device_id: Option<i64>,
    pub probe_id: Option<i64>,
    pub r#type: String,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub configuration: Json,
    pub interval_seconds: i32,
    pub timeout_seconds: i32,
    pub retry_count: i32,
    pub enabled: bool,
    pub next_run_at: Option<DateTimeWithTimeZone>,
    pub last_run_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alert_events::Entity")]
    AlertEvents,
    #[sea_orm(has_many = "super::alert_rules::Entity")]
    AlertRules,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(has_many = "super::metrics::Entity")]
    Metrics,
    #[sea_orm(has_many = "super::monitor_results::Entity")]
    MonitorResults,
    #[sea_orm(has_one = "super::probe_tasks::Entity")]
    ProbeTasks,
    #[sea_orm(
        belongs_to = "super::probes::Entity",
        from = "Column::ProbeId",
        to = "super::probes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Probes,
}

impl Related<super::alert_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertEvents.def()
    }
}

impl Related<super::alert_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertRules.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::metrics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Metrics.def()
    }
}

impl Related<super::monitor_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MonitorResults.def()
    }
}

impl Related<super::probe_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProbeTasks.def()
    }
}

impl Related<super::probes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Probes.def()
    }
}
