//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "networks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub site_id: Option<i64>,
    pub probe_id: Option<i64>,
    pub name: String,
    pub cidr: String,
    pub gateway: Option<String>,
    pub vlan: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub dns_servers: Option<Json>,
    pub scan_enabled: bool,
    pub scan_interval: i32,
    pub active: bool,
    pub last_scan_at: Option<DateTimeWithTimeZone>,
    pub next_scan_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
    #[sea_orm(has_many = "super::discovery_runs::Entity")]
    DiscoveryRuns,
    #[sea_orm(
        belongs_to = "super::probes::Entity",
        from = "Column::ProbeId",
        to = "super::probes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Probes,
    #[sea_orm(
        belongs_to = "super::sites::Entity",
        from = "Column::SiteId",
        to = "super::sites::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sites,
    #[sea_orm(has_many = "super::vpn_servers::Entity")]
    VpnServers,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::discovery_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscoveryRuns.def()
    }
}

impl Related<super::probes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Probes.def()
    }
}

impl Related<super::sites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sites.def()
    }
}

impl Related<super::vpn_servers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VpnServers.def()
    }
}
