//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::alert_events::Entity as AlertEvents;
pub use super::alert_rules::Entity as AlertRules;
pub use super::device_interfaces::Entity as DeviceInterfaces;
pub use super::device_links::Entity as DeviceLinks;
pub use super::devices::Entity as Devices;
pub use super::discovery_results::Entity as DiscoveryResults;
pub use super::discovery_runs::Entity as DiscoveryRuns;
pub use super::dns_servers::Entity as DnsServers;
pub use super::event_outbox::Entity as EventOutbox;
pub use super::metrics::Entity as Metrics;
pub use super::monitor_results::Entity as MonitorResults;
pub use super::monitors::Entity as Monitors;
pub use super::networks::Entity as Networks;
pub use super::probe_tasks::Entity as ProbeTasks;
pub use super::probes::Entity as Probes;
pub use super::sites::Entity as Sites;
pub use super::system_settings::Entity as SystemSettings;
pub use super::users::Entity as Users;
pub use super::vpn_peers::Entity as VpnPeers;
pub use super::vpn_servers::Entity as VpnServers;
pub use super::zabbix_template_items::Entity as ZabbixTemplateItems;
pub use super::zabbix_templates::Entity as ZabbixTemplates;
