//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "probes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub site_id: Option<i64>,
    pub name: String,
    pub token_hash: String,
    pub status: String,
    pub version: Option<String>,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub registered_at: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub configuration: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discovery_runs::Entity")]
    DiscoveryRuns,
    #[sea_orm(has_many = "super::monitor_results::Entity")]
    MonitorResults,
    #[sea_orm(has_many = "super::monitors::Entity")]
    Monitors,
    #[sea_orm(has_many = "super::networks::Entity")]
    Networks,
    #[sea_orm(has_many = "super::probe_tasks::Entity")]
    ProbeTasks,
    #[sea_orm(
        belongs_to = "super::sites::Entity",
        from = "Column::SiteId",
        to = "super::sites::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sites,
}

impl Related<super::discovery_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscoveryRuns.def()
    }
}

impl Related<super::monitor_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MonitorResults.def()
    }
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}

impl Related<super::networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networks.def()
    }
}

impl Related<super::probe_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProbeTasks.def()
    }
}

impl Related<super::sites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sites.def()
    }
}
