//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vpn_peers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub vpn_server_id: i64,
    #[sea_orm(unique)]
    pub device_id: i64,
    #[sea_orm(unique)]
    pub public_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub preshared_key_encrypted: Option<String>,
    pub device_profile: String,
    pub persistent_keepalive: i32,
    pub last_handshake_at: Option<DateTimeWithTimeZone>,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub bytes_rx: i64,
    pub bytes_tx: i64,
    pub enabled: bool,
    pub last_connection_status: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::vpn_servers::Entity",
        from = "Column::VpnServerId",
        to = "super::vpn_servers::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VpnServers,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::vpn_servers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VpnServers.def()
    }
}
