//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vpn_servers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub network_id: i64,
    pub interface_name: String,
    pub listen_port: i32,
    pub public_endpoint: Option<String>,
    pub public_key: String,
    #[sea_orm(column_type = "Text")]
    pub private_key_encrypted: String,
    pub allow_peer_to_peer: bool,
    pub mtu: i32,
    pub dns_servers: Option<String>,
    pub active: bool,
    pub last_synced_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::networks::Entity",
        from = "Column::NetworkId",
        to = "super::networks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Networks,
    #[sea_orm(has_many = "super::vpn_peers::Entity")]
    VpnPeers,
}

impl Related<super::networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networks.def()
    }
}

impl Related<super::vpn_peers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VpnPeers.def()
    }
}
