//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "zabbix_templates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub zabbix_uuid: Option<String>,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub zabbix_version: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub raw_export: Json,
    pub imported_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
    #[sea_orm(has_many = "super::zabbix_template_items::Entity")]
    ZabbixTemplateItems,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::zabbix_template_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZabbixTemplateItems.def()
    }
}
