//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "zabbix_template_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub template_id: i64,
    pub zabbix_uuid: Option<String>,
    pub name: String,
    pub key: String,
    pub snmp_oid: String,
    pub value_type: String,
    pub units: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub multiplier: Option<f32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::zabbix_templates::Entity",
        from = "Column::TemplateId",
        to = "super::zabbix_templates::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ZabbixTemplates,
}

impl Related<super::zabbix_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZabbixTemplates.def()
    }
}
