// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma medida numérica produzida por um checker.
 */
export type CheckMetric = { name: string, value: number, unit: string, };
