// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckMetric } from "./CheckMetric";
import type { MonitorStatus } from "./MonitorStatus";

/**
 * Resultado degradável de uma medição. Erro de rede é dado de domínio, não panic.
 */
export type CheckResult = { success: boolean, status: MonitorStatus, startedAt: string, finishedAt: string, durationMs: bigint, message: string | null, metrics: Array<CheckMetric>, data: any, };
