// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado canônico de uma execução de monitor.
 */
export type MonitorStatus = "up" | "down" | "warning" | "unknown" | "disabled";
