/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Alerts: () => import('#controllers/alerts_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Devices: () => import('#controllers/devices_controller'),
  Discovery: () => import('#controllers/discovery_controller'),
  Events: () => import('#controllers/events_controller'),
  Monitors: () => import('#controllers/monitors_controller'),
  Networks: () => import('#controllers/networks_controller'),
  Probes: () => import('#controllers/probes_controller'),
  Sites: () => import('#controllers/sites_controller'),
  Snmp: () => import('#controllers/snmp_controller'),
  Topology: () => import('#controllers/topology_controller'),
}
