// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { TransportKind } from "./TransportKind";

/**
 * O que o runtime quer fazer, do jeito que o operador lê.
 */
export type AccessRequest = { transport: TransportKind, 
/**
 * `opkg install luci-app-sqm`, `POST /cgi-bin/luci` — já sem segredos.
 */
summary: string, effect: Effect, 
/**
 * Por que (declarado pela IA ou pela ação do plugin).
 */
reason?: string, };
