// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta ao agente que trocou o código.
 */
export type AgentEnrollResponse = { probeId: number; name: string; token: string }
