// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Troca do código de enrollment pelo token (chamada pelo próprio agente).
 */
export type AgentEnrollInput = { code: string; hostname: string | null }
