// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alteração do cadastro.
 */
export type AgentUpdateInput = {
  name: string | null
  deviceId: number | null
  enforceTunnelIp: boolean | null
}
