// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEnrollmentView } from './AgentEnrollmentView'
import type { AgentView } from './AgentView'

export type AgentWithEnrollment = { agent: AgentView; enrollment: AgentEnrollmentView }
