// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Regera os comandos de instalação para outro endereço desta central.
 */
export type AgentInstallCommandsInput = {
  code: string
  /**
   * Id de uma entrada de "Endereços deste servidor".
   */
  addressId: string
}
