// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInstallCommands } from './AgentInstallCommands'

/**
 * Instruções entregues uma única vez, junto com o código de enrollment.
 */
export type AgentEnrollmentView = {
  code: string
  expiresInSeconds: number
  commands: AgentInstallCommands
}
