// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agente remoto por onde o acesso pode sair.
 */
export type AgentRouteOption = { id: number, name: string, connected: boolean, 
/**
 * O agente anunciou `device_io` no `AGENT_ALLOW`.
 */
allowsDeviceIo: boolean, };
