// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agente remoto por onde um acesso pode sair (plugin de dispositivo, ponte
 * de banco). A tela desabilita quem não serve e diz por quê.
 */
export type AgentRouteOption = { id: number, name: string, connected: boolean, 
/**
 * O agente anunciou a permissão do recurso no `AGENT_ALLOW`.
 */
allowed: boolean, };
