// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCapabilityView } from './AgentCapabilityView'
import type { Permission } from './Permission'

/**
 * O que a última conexão do agente anunciou (guardado em
 * `probes.configuration`).
 */
export type AgentHostInfo = {
  hostname: string | null
  os: string | null
  arch: string | null
  inContainer: boolean
  policy: Array<Permission>
  docker: AgentCapabilityView
  compose: AgentCapabilityView
}
