// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHostInfo } from './AgentHostInfo'

export type AgentView = {
  id: number
  name: string
  /**
   * Chave do host Docker deste agente (`agent-<id>`).
   */
  hostKey: string
  siteId: number | null
  deviceId: number | null
  deviceName: string | null
  deviceIp: string | null
  status: string
  /**
   * Canal aberto com este processo agora.
   */
  connected: boolean
  version: string | null
  lastSeenAt: string | null
  registeredAt: string | null
  enforceTunnelIp: boolean
  host: AgentHostInfo
  createdAt: string
}
