// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amostra de uma série: instante em RFC 3339 e valor na unidade do gráfico.
 */
export type AiChartPoint = { time: string; value: number }
