// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amostra de uma série: instante RFC 3339 (ou rótulo, conforme o eixo) e
 * valor na unidade do gráfico.
 */
export type AiChartPoint = { time: string; value: number }
