// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiChartPoint } from './AiChartPoint'

export type AiChartSeries = { id: string; label: string; points: Array<AiChartPoint> }
