// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiChartAxis } from './AiChartAxis'
import type { AiChartSeries } from './AiChartSeries'
import type { AiChartUnit } from './AiChartUnit'

/**
 * Gráfico produzido por uma ferramenta da IA e desenhado no chat com o
 * mesmo componente das telas de monitor e interface.
 *
 * Os pontos vão só para a tela; a IA recebe o resumo estatístico.
 */
export type AiChart = {
  title: string
  subtitle: string | null
  unit: AiChartUnit
  xAxis: AiChartAxis
  series: Array<AiChartSeries>
  avgValue: number | null
}
