// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grandeza do eixo Y de um gráfico da IA — o frontend escolhe o formatador por ela.
 */
export type AiChartUnit = 'latency' | 'bandwidth' | 'percentage' | 'generic'
