// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de criação/atualização de uma conversa salva do assistente.
 */
export type AiConversationInput = {
  title: string
  /**
   * Mensagens como a tela as exibe (texto, ferramentas, gráficos).
   */
  messages: unknown[]
}
