// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item da lista de conversas: sem as mensagens, que só vêm ao abrir.
 */
export type AiConversationSummary = { id: number, title: string, updatedAt: string, messageCount: number, };
