// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que a IA pode fazer com containers Docker (iniciar, parar, reiniciar).
 */
export type AiContainerActionMode = 'off' | 'confirm' | 'auto'
