// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frequência do resumo da rede enviado pelos canais de notificação.
 */
export type AiDigestSchedule = 'off' | 'daily' | 'weekly'
