// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiDigest = {
  text: string
  generatedAt: string
  periodHours: number
  promptTokens: number
  completionTokens: number
}
