// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaFeatures } from "./LayaFeatures";

export type AiLayaSettings = { 
/**
 * Chave mestra: desligado, nenhuma frente consulta o Laya.
 */
enabled: boolean, baseUrl: string, model: string, 
/**
 * 1–99: quanto maior, menos grupos entram por palpite do Laya.
 */
minConfidence: number, 
/**
 * 200–10.000 ms.
 */
timeoutMs: number, features: LayaFeatures, };
