// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiLayaSettings = {
  /**
   * Decide, antes de cada pergunta, quais grupos de ferramentas vão à IA.
   */
  enabled: boolean
  baseUrl: string
  model: string
  /**
   * 1–99: quanto maior, menos grupos entram por palpite do Laya.
   */
  minConfidence: number
  /**
   * 200–10.000 ms.
   */
  timeoutMs: number
}
