// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMentionKind } from './AiMentionKind'

/**
 * Algo marcado com `@` na pergunta: diz à IA de qual recurso se trata, sem
 * ela precisar adivinhar pelo nome.
 */
export type AiMention = {
  kind: AiMentionKind
  /**
   * Id do dispositivo/monitor, id do container ou nome da fonte.
   */
  id: string
  label: string
  /**
   * Linha curta para a lista de sugestões (IP, tipo, estado).
   */
  detail?: string
}
