// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tipo do que se marca com `@` no chat.
 */
export type AiMentionKind = 'device' | 'monitor' | 'container' | 'source'
