// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiDigestSchedule } from './AiDigestSchedule'
import type { AiIncidentSeverity } from './AiIncidentSeverity'

export type AiProactiveSettings = {
  /**
   * Gera um resumo (causa provável e primeira ação) quando um alerta abre.
   */
  incidentSummaries: boolean
  incidentMinSeverity: AiIncidentSeverity
  /**
   * Teto de resumos automáticos por hora, para uma tempestade de alertas
   * não virar uma tempestade de chamadas ao provedor.
   */
  maxSummariesPerHour: number
  digest: AiDigestSchedule
  /**
   * Hora (0–23, horário do servidor) em que o resumo periódico sai.
   */
  digestHour: number
  /**
   * Não gastar tokens com resumo periódico de um período em que nenhum
   * alerta abriu e nenhum ficou aberto — "nada aconteceu" se conta, não se
   * pergunta ao LLM.
   */
  skipQuietDigest: boolean
}
