// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { Severity } from "./Severity";

/**
 * O que a IA concluiu.
 */
export type AiReview = { riskLevel: Severity, summary: string, findings: Array<Finding>, 
/**
 * O script faz algo que o `usage` não descreve.
 */
mismatchWithUsage: boolean, model?: string, };
