// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiResponseStyle } from './AiResponseStyle'

export type AiSettings = {
  enabled: boolean
  /**
   * Driver ativo: "opencode" | "openrouter" | "ollama"
   */
  activeDriver: string
  opencodeBaseUrl: string | null
  opencodeApiKey: string | null
  opencodeModel: string | null
  openrouterApiKey: string | null
  openrouterModel: string | null
  ollamaBaseUrl: string | null
  ollamaModel: string | null
  /**
   * Permite executar ferramentas ativas (ping, traceroute, scan de portas)
   */
  allowActiveTools: boolean
  /**
   * Exige confirmação do usuário antes de rodar ferramentas ativas
   */
  requireToolConfirmation: boolean
  /**
   * Quanto texto a IA devolve: direto (mínimo de tokens) ou normal.
   */
  responseStyle: AiResponseStyle
  customSystemPrompt: string | null
}
