// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiContainerActionMode } from './AiContainerActionMode'
import type { AiProactiveSettings } from './AiProactiveSettings'
import type { AiResponseStyle } from './AiResponseStyle'

export type AiSettings = {
  enabled: boolean
  /**
   * Driver ativo: "opencode" | "openrouter" | "ollama"
   */
  activeDriver: string
  opencodeBaseUrl: string | null
  opencodeApiKey: string | null
  opencodeModel: string | null
  openrouterApiKey: string | null
  openrouterModel: string | null
  ollamaBaseUrl: string | null
  ollamaModel: string | null
  /**
   * Permite executar ferramentas ativas (ping, traceroute, scan de portas)
   */
  allowActiveTools: boolean
  /**
   * Exige confirmação do usuário antes de rodar ferramentas ativas
   */
  requireToolConfirmation: boolean
  /**
   * Permite que a IA proponha ações (reconhecer/silenciar alerta, janela de
   * manutenção, criar monitor). Toda ação passa pela confirmação do usuário.
   */
  allowActions: boolean
  /**
   * Iniciar, parar e reiniciar containers: desligado, com confirmação
   * (padrão) ou automático.
   */
  containerActions: AiContainerActionMode
  /**
   * Quanto texto a IA devolve: direto (mínimo de tokens) ou normal.
   */
  responseStyle: AiResponseStyle
  /**
   * O que a IA faz sozinha: resumo de incidente e resumo periódico.
   */
  proactive: AiProactiveSettings
  customSystemPrompt: string | null
}
