// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um `condition.field` válido.
 *
 * A ordem é a de [`crate::services::alerts::fields::ALERT_FIELDS`], que é a
 * ordem em que os campos aparecem no seletor da tela.
 */
export type AlertField =
  | 'status'
  | 'latencyMs'
  | 'packetLoss'
  | 'statusCode'
  | 'durationMs'
  | 'connectTimeMs'
  | 'resolutionTimeMs'
  | 'ifOperStatus'
  | 'ifSpeed'
  | 'snmpUptime'
  | 'inBps'
  | 'outBps'
  | 'cpuUsagePercent'
  | 'memoryUsedPercent'
  | 'storageUsedPercent'
  | 'loadAverage1m'
  | 'interfaceName'
  | 'interfaceOperStatus'
  | 'interfaceStatusTransition'
  | 'interfaceSpeedBps'
  | 'interfaceSpeedTransition'
  | 'interfaceSpeedDropPercent'
  | 'vpnPeerName'
  | 'vpnPeerStatus'
  | 'vpnStatusTransition'
  | 'vpnSecondsSinceActivity'
  | 'logPatternKey'
  | 'logMatchCount'
  | 'logWindowSeconds'
  | 'logSeverity'
  | 'logMessage'
  | 'success'
  | 'type'
