// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiFieldError } from './ApiFieldError'

/**
 * Corpo de erro da API (§5.5).
 *
 * É o espelho de `ApiErrorResponse` em `frontend/src/services/apiService.ts`:
 * o cliente lê `message` e, na ausência dela, junta `errors[].message`. Quem
 * produz esta forma em runtime é o `IntoResponse` de
 * [`crate::services::shared::errors::AppError`]; este struct existe para
 * documentar o contrato e gerar o binding TypeScript.
 */
export type ApiError = { message: string; errors: Array<ApiFieldError> | null }
