// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alternativa de instalação entregue ao lado do artefato principal — o mesmo
 * túnel, porém escrito para outro gerenciador de pacotes. Cada variante é
 * autocontida: instala o cliente, grava o perfil e sobe o túnel.
 */
export type ArtifactVariant = { 
/**
 * Identificador estável usado como chave de aba no frontend.
 */
id: string, label: string, 
/**
 * Onde essa variante se aplica (ex.: "Debian, Ubuntu, Mint").
 */
hint: string, icon: string, fileName: string, language: string, content: string, instructions: Array<string>, };
