// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Par rótulo/valor exibido no resumo "os dados do túnel" antes do script.
 */
export type ArtifactSummaryItem = { label: string; value: string }
