// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditLogResponse = { id: number, userId: number | null, userEmail: string | null, action: string, resourceType: string | null, resourceId: number | null, resourceLabel: string | null, description: string | null, changes: any, ipAddress: string | null, userAgent: string | null, createdAt: string, };
