// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogResponse } from './AuditLogResponse'
import type { PaginationMeta } from './PaginationMeta'

export type AuditLogListResponse = { data: Array<AuditLogResponse>; meta: PaginationMeta }
