// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoAcceptInput = { conversationKey: string, deviceId: number, 
/**
 * Marcou "Estou ciente" no termo.
 */
acceptTerms: boolean, };
