// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoAcceptState = { active: boolean, expiresAt: string | null, termsVersion: string, 
/**
 * O texto do termo, para a tela mostrar exatamente o que é aceito.
 */
terms: string, };
