// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTableCount } from "./BackupTableCount";

/**
 * `{"tables": [{"table": "...", "rows": n}], "totalRows": n}`.
 */
export type BackupCountsResponse = { tables: Array<BackupTableCount>, totalRows: number, };
