// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ponto da série de correlação banda x latência.
 */
export type BandwidthLatencyPoint = {
  time: string
  timestamp: number
  bwBps: number
  latency: number
}
