// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandwidthLatencyPoint } from './BandwidthLatencyPoint'

/**
 * Resposta do endpoint de correlação banda x latência.
 */
export type BandwidthLatencyResponse = {
  timeframe: string
  samples: Array<BandwidthLatencyPoint>
  currentBw: number
  peakBw: number
  currentLatency: number
  avgLatency: number
  correlationScore: number
  hasSaturationCorrelation: boolean
}
