// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um equipamento dentro de um lote de frota.
 */
export type BatchDevice = { deviceId: number, deviceName: string, runId: number | null, 
/**
 * `pending`, `running`, `succeeded`, `failed` ou `skipped`.
 */
status: string, error: string | null, output: unknown, };
