// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta do vínculo/desvínculo manual de uma origem de syslog.
 */
export type BindSourceResponse = { bindKey: string; deviceId: number | null }
