// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageInput } from "./ChatMessageInput";

export type ChatStreamRequest = { messages: Array<ChatMessageInput>, deviceId: bigint | null, };
