// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMention } from './AiMention'
import type { ChatMessageInput } from './ChatMessageInput'
import type { ContextHint } from './ContextHint'

export type ChatStreamRequest = {
  messages: Array<ChatMessageInput>
  /**
   * Dispositivo, monitor ou alerta de onde o chat foi aberto: vira contexto
   * no system prompt para a IA não precisar perguntar "qual?".
   */
  deviceId: number | null
  monitorId: number | null
  alertId: number | null
  /**
   * O que o usuário marcou com `@` na última pergunta.
   */
  mentions: Array<AiMention>
  /**
   * Resumo das mensagens já compactadas — elas não vêm mais em `messages`.
   */
  summary: string | null
  /**
   * O que a resposta anterior mediu: base da decisão de compactar.
   */
  contextHint: ContextHint | null
  /**
   * Compactar agora, mesmo cabendo na janela.
   */
  compact: boolean
}
