// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMention } from './AiMention'
import type { ChatMessageInput } from './ChatMessageInput'

export type ChatStreamRequest = {
  messages: Array<ChatMessageInput>
  /**
   * Dispositivo, monitor ou alerta de onde o chat foi aberto: vira contexto
   * no system prompt para a IA não precisar perguntar "qual?".
   */
  deviceId: number | null
  monitorId: number | null
  alertId: number | null
  /**
   * O que o usuário marcou com `@` na última pergunta.
   */
  mentions: Array<AiMention>
}
