// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estatísticas retornadas por `POST /api/settings/clear-all-items`.
 */
export type ClearAllItemsStats = {
  devicesDeleted: bigint
  monitorsDeleted: bigint
  networksDeleted: bigint
  totalDeleted: bigint
}
