// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um serviço do projeto e o estado dos containers dele (réplicas incluídas).
 */
export type ComposeService = { name: string; containers: number; running: number }
