// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um equipamento em que o plugin já foi validado.
 */
export type CompatEntry = { platform?: string, vendor?: string, model?: string, firmware?: string, 
/**
 * `passed` ou `failed`.
 */
status: string, validatedAt: string, 
/**
 * Versão do plugin validada.
 */
pluginVersion: string, 
/**
 * Execução que comprova (só faz sentido na instalação de origem).
 */
runId?: number, };
