// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeService } from './ComposeService'

export type ComposeProject = {
  name: string
  workingDir: string
  configFiles: Array<string>
  services: Array<ComposeService>
  containers: number
  running: number
}
