// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerUsageSummary = {
  name: string
  project: string | null
  cpuAvg: number
  cpuMax: number
  memoryMax: number
  netRxBytes: number
  netTxBytes: number
}
