// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerHistoryPoint = {
  at: string
  cpuAvg: number
  cpuMax: number
  memoryAvg: number
  memoryMax: number
  netRxBytes: number
  netTxBytes: number
  blockReadBytes: number
  blockWriteBytes: number
}
