// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerHistoryPoint } from './ContainerHistoryPoint'
import type { MetricsRange } from './MetricsRange'

export type ContainerHistoryResponse = {
  hostKey: string
  containerName: string
  range: MetricsRange
  stepMinutes: number
  points: Array<ContainerHistoryPoint>
}
