// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretStorage } from "./SecretStorage";
import type { TransportKind } from "./TransportKind";

export type CredentialInput = { kind: TransportKind, username: string, 
/**
 * Vazio mantém a senha guardada (no `vault`).
 */
secret?: string, storage: SecretStorage, port?: number, https?: boolean, viaProbeId?: number | null, };
