// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretStorage } from "./SecretStorage";
import type { TransportKind } from "./TransportKind";

/**
 * O que a tela vê. Sem senha, nunca.
 */
export type CredentialView = { kind: TransportKind, username: string, storage: SecretStorage, port: number, 
/**
 * HTTPS em vez de HTTP (só para `http`).
 */
https: boolean, viaProbeId: number | null, 
/**
 * Há senha cifrada guardada.
 */
hasStoredSecret: boolean, 
/**
 * Há senha de sessão em memória, ainda válida.
 */
sessionActive: boolean, };
