// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma linha do histórico.
 */
export type DatabaseBackupResponse = { id: number, connectionId: number, databaseName: string, storageDestinationId: number | null, objectKey: string | null, sizeBytes: number | null, checksum: string | null, tables: number, rows: number, durationMs: number, 
/**
 * `running` | `success` | `failed`.
 */
status: string, error: string | null, warnings: Array<string>, 
/**
 * `manual` | `scheduled`.
 */
trigger: string, startedAt: string, finishedAt: string | null, };
