// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseEngine } from "./DatabaseEngine";
import type { SslMode } from "./SslMode";

/**
 * "Testar e listar bancos" do formulário.
 */
export type DatabaseProbeInput = { 
/**
 * Conexão em edição: senha vazia vem dela.
 */
id?: number | null, engine: DatabaseEngine, host: string, port: number, username: string, password?: string, sslMode: SslMode, 
/**
 * Testar pela ponte deste agente.
 */
viaProbeId?: number | null, };
