// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseJobKind } from "./DatabaseJobKind";
import type { DatabaseJobStatus } from "./DatabaseJobStatus";

/**
 * O que a tela mostra de uma execução em curso ou recém-terminada.
 *
 * Sem host, usuário ou senha: o barramento SSE chega a toda sessão aberta.
 */
export type DatabaseJobSnapshot = { id: string, kind: DatabaseJobKind, connectionId: number, 
/**
 * Banco em curso.
 */
database: string | null, stage: string, rows: number, bytes: number, databasesDone: number, databasesTotal: number, status: DatabaseJobStatus, message: string | null, startedAt: string, finishedAt: string | null, };
