// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseEngine } from "./DatabaseEngine";
import type { SslMode } from "./SslMode";

export type DatabaseConnectionResponse = { id: number, name: string, engine: DatabaseEngine, host: string, port: number, username: string, passwordSet: boolean, sslMode: SslMode, 
/**
 * Vazio é "todos os bancos".
 */
databases: Array<string>, storageDestinationId: number | null, storageDestinationName: string | null, backupEnabled: boolean, backupIntervalHours: number, backupRetention: number, lastBackupAt: string | null, 
/**
 * `success` | `failed`.
 */
lastBackupStatus: string | null, lastBackupError: string | null, nextBackupAt: string | null, createdAt: string, updatedAt: string, };
