// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseEngine } from "./DatabaseEngine";
import type { SslMode } from "./SslMode";

/**
 * Formulário de criação e edição.
 */
export type DatabaseConnectionInput = { name: string, engine: DatabaseEngine, host: string, port: number, username: string, password?: string, sslMode: SslMode, 
/**
 * Vazio é "todos os bancos".
 */
databases: Array<string>, storageDestinationId: number | null, 
/**
 * "Acessar a partir de": agente pelo qual a central chega ao banco;
 * nulo é direto (ADR 013).
 */
viaProbeId: number | null, backupEnabled: boolean, backupIntervalHours: number, backupRetention: number, };
