// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreMode } from "./RestoreMode";

/**
 * Restaurar uma cópia.
 */
export type DatabaseRestoreInput = { targetConnectionId: number, database: string, mode: RestoreMode, 
/**
 * No modo substituir, o nome do banco digitado de novo — a mesma
 * confirmação que a tela pede, conferida aqui também.
 */
confirmDatabase?: string, };
