// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbType } from './DbType'

/**
 * Dados retornados por `GET /api/settings/database-size`.
 */
export type DatabaseInfo = { dbType: DbType; sizeBytes: bigint }
