// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evento de alerta de um dispositivo exibido na aba de eventos.
 */
export type DeviceEventItem = {
  id: number
  deviceId: number
  eventType: string
  severity: string
  message: string
  createdAt: string
}
