// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compat } from "./Compat";
import type { PluginSummary } from "./PluginSummary";

/**
 * Um plugin do ponto de vista de um equipamento.
 */
export type DevicePluginItem = { plugin: PluginSummary, compat: Compat, reasons: Array<string>, 
/**
 * Instalado neste equipamento: ganha a própria aba.
 */
installed: boolean, installedAt: string | null, 
/**
 * Ajuste deste equipamento (segredos mascarados), quando o plugin tem.
 */
deviceSettings: Record<string, unknown> | null, };
