// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Métrica de um dispositivo exibida na aba de métricas.
 */
export type DeviceMetricItem = { id: number, deviceId: number, interfaceId: number | null, interfaceName: string | null, metricName: string, metricValue: number, unit: string, createdAt: string, };
