// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParentRef } from './ParentRef'
import type { SiteRef } from './SiteRef'

/**
 * Projeção canônica completa de um dispositivo para a API HTTP.
 */
export type DevicePresenterItem = {
  id: number
  siteId: number | null
  networkId: number | null
  parentId: number | null
  ipAddress: string | null
  name: string
  type: string
  vendor: string | null
  model: string | null
  serialNumber: string | null
  description: string | null
  isMonitored: boolean
  snmpEnabled: boolean
  snmpCommunity: string | null
  snmpVersion: string | null
  snmpPollIntervalSeconds: number
  status: string
  accessMode: string | null
  effectiveAccessMode: string
  accessModeReason: string
  accessModeDeclared: boolean
  operatingSystem: string | null
  effectiveOperatingSystem: string
  operatingSystemSource: string
  operatingSystemReason: string
  lastSeenAt: string | null
  createdAt: string
  updatedAt: string
  site: SiteRef | null
  parent: ParentRef | null
  systemKey: string | null
  isSystem: boolean
  linkInterfaceId: number | null
  linkInterfaceName: string | null
  vpnPeer: any
}
