// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRouteOption } from "./AgentRouteOption";
import type { CredentialView } from "./CredentialView";
import type { DevicePluginItem } from "./DevicePluginItem";
import type { PluginRunView } from "./PluginRunView";

/**
 * Tudo que a aba "Plugins" de `/devices/{id}` precisa.
 */
export type DevicePluginsView = { deviceId: number, 
/**
 * Sistema efetivo do equipamento (`openwrt`, `linux`, …).
 */
platform: string, firmware: string | null, plugins: Array<DevicePluginItem>, credentials: Array<CredentialView>, runs: Array<PluginRunView>, agents: Array<AgentRouteOption>, };
