// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uso de um ponto de montagem no instante da amostra.
 */
export type DiskUsage = { mount: string; usedBytes: number; totalBytes: number }
