// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerRestartPolicy } from './DockerRestartPolicy'

export type DockerContainerHostConfig = { restartPolicy: DockerRestartPolicy; networkMode: string }
