// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerLogEntry } from './DockerLogEntry'

/**
 * Linha de log em follow publicada no SSE como `docker:log`.
 */
export type DockerLogStreamEvent = {
  streamId: string
  hostKey: string
  containerId: string
  entries: Array<DockerLogEntry>
  /**
   * Presente quando o stream terminou.
   */
  ended: string | null
}
