// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerVolumeDetail = {
  name: string
  driver: string
  mountpoint: string
  labels: { [key in string]: string }
  scope: string
  createdAt: string | null
  options: { [key in string]: string }
}
