// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma operação longa (pull, update, compose) aceita pela central.
 */
export type DockerOperationAccepted = {
  operationId: string
  hostKey: string
  kind: string
  target: string
}
