// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerImageSummary } from './DockerImageSummary'
import type { DockerNetworkSummary } from './DockerNetworkSummary'
import type { DockerVolumeSummary } from './DockerVolumeSummary'

export type DockerInventorySnapshot = {
  collectedAt: string
  volumes: Array<DockerVolumeSummary>
  networks: Array<DockerNetworkSummary>
  images: Array<DockerImageSummary>
}
