// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerMount = {
  mountType: string
  name: string | null
  source: string
  destination: string
  mode: string
  readWrite: boolean
}
