// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsRange } from './MetricsRange'

export type DockerHistoryQuery = { range: MetricsRange | null }
