// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerContainerMetrics } from './DockerContainerMetrics'

export type DockerMetricsResponse = {
  dockerAvailable: boolean
  unavailableReason: string | null
  collectedAt: string
  containers: Array<DockerContainerMetrics>
}
