// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerImageDetail = {
  id: string
  repoTags: Array<string>
  created: string
  size: number
  environment: Array<string>
  command: Array<string>
  entrypoint: Array<string>
  labels: { [key in string]: string }
  workingDir: string
  user: string
  rootFsType: string
  layers: Array<string>
}
