// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerContainerPort = {
  ip: string | null
  privatePort: number
  publicPort: number | null
  protocol: string
}
