// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerImageSummary = {
  id: string
  parentId: string
  repoTags: Array<string>
  repoDigests: Array<string>
  created: number
  size: number
  sharedSize: number
  labels: { [key in string]: string }
  containers: number
}
