// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerContainerState = {
  status: string
  running: boolean
  paused: boolean
  restarting: boolean
  pid: number
  startedAt: string
  finishedAt: string
  exitCode: number
}
