// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerNetworkContainer = {
  containerId: string
  name: string
  macAddress: string
  ipv4Address: string
  ipv6Address: string
}
