// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerIpamConfig } from './DockerIpamConfig'
import type { DockerNetworkContainer } from './DockerNetworkContainer'

export type DockerNetworkDetail = {
  id: string
  name: string
  driver: string
  scope: string
  ipamDriver: string
  ipamConfig: Array<DockerIpamConfig>
  internal: boolean
  connectedContainers: number
  labels: { [key in string]: string }
  created: string
  containers: Array<DockerNetworkContainer>
  options: { [key in string]: string }
}
