// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progresso publicado no SSE como `docker:operation`.
 */
export type DockerOperationEvent = {
  operationId: string
  hostKey: string
  kind: string
  target: string
  /**
   * `running`, `succeeded` ou `failed`.
   */
  state: string
  line: string | null
  message: string | null
}
