// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from './Permission'

/**
 * Um host Docker disponível para a tela: a própria central ou um agente.
 */
export type DockerHostView = {
  key: string
  name: string
  kind: string
  online: boolean
  agentId: number | null
  dockerAvailable: boolean
  composeAvailable: boolean
  policy: Array<Permission>
}
