// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerContainerConfig } from './DockerContainerConfig'
import type { DockerContainerHostConfig } from './DockerContainerHostConfig'
import type { DockerContainerState } from './DockerContainerState'
import type { DockerMount } from './DockerMount'
import type { DockerNetworkEndpoint } from './DockerNetworkEndpoint'

export type DockerContainerDetail = {
  id: string
  name: string
  image: string
  imageId: string
  created: string
  state: DockerContainerState
  config: DockerContainerConfig
  hostConfig: DockerContainerHostConfig
  mounts: Array<DockerMount>
  networks: Array<DockerNetworkEndpoint>
}
