// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerStatusResponse = {
  available: boolean
  reason: string | null
  engineVersion: string | null
  apiVersion: string | null
  name: string | null
  operatingSystem: string | null
  architecture: string | null
  cpus: number | null
  memoryTotalBytes: number | null
  containers: number | null
  containersRunning: number | null
  containersStopped: number | null
  images: number | null
}
