// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerNetworkEndpoint = {
  networkId: string
  networkName: string
  ipAddress: string
  gateway: string
  aliases: Array<string>
}
