// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerCpuMetrics } from './DockerCpuMetrics'
import type { DockerIoMetrics } from './DockerIoMetrics'
import type { DockerMemoryMetrics } from './DockerMemoryMetrics'
import type { DockerNetworkMetrics } from './DockerNetworkMetrics'

export type DockerContainerMetrics = {
  containerId: string
  containerName: string
  projectName: string | null
  imageName: string
  status: string
  cpu: DockerCpuMetrics
  memory: DockerMemoryMetrics
  network: DockerNetworkMetrics
  blockIo: DockerIoMetrics
  pids: number | null
}
