// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerContainerPort } from './DockerContainerPort'

export type DockerContainerSummary = {
  id: string
  names: Array<string>
  image: string
  imageId: string
  state: string
  status: string
  labels: { [key in string]: string }
  ports: Array<DockerContainerPort>
  created: number
  projectName: string | null
}
