// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerContainerSummary } from './DockerContainerSummary'
import type { DockerMetricsResponse } from './DockerMetricsResponse'
import type { DockerStatusResponse } from './DockerStatusResponse'

export type DockerLiveSnapshot = {
  status: DockerStatusResponse
  containers: Array<DockerContainerSummary>
  metrics: DockerMetricsResponse
}
