// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiChart } from './AiChart'

export type ExecuteToolResponse = { result: Record<string, unknown>; chart: AiChart | null }
