// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de `POST /api/ai/tools/execute`: a chamada que o usuário confirmou.
 */
export type ExecuteToolRequest = { name: string; arguments: Record<string, unknown> }
