// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type Finding = { severity: Severity, 
/**
 * Identificador da regra (`flash-write`) ou `ai` para achado da IA.
 */
rule: string, message: string, line?: number, excerpt?: string, };
