// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma resposta gravada do equipamento, para o teste unitário.
 *
 * Exatamente um de `ssh`, `telnet` ou `http` identifica a chamada; o resto é
 * a resposta. `http` é `"MÉTODO /caminho"`.
 */
export type Fixture = { ssh?: string, telnet?: string, http?: string, 
/**
 * Trata a chave (`ssh`/`telnet`/`http`) como regex em vez de texto exato.
 */
regex: boolean, stdout: string, stderr: string, exit: number, status: number, body: string, headers?: Record<string, string>, };
