// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compat } from "./Compat";

/**
 * Um equipamento da frota.
 */
export type FleetMember = { deviceId: number, name: string, ip: string | null, platform: string, firmware: string | null, compat: Compat, installedAt: string, 
/**
 * Há credencial pronta para os transportes do plugin.
 */
credentialsReady: boolean, 
/**
 * Ajuste deste equipamento (segredos mascarados).
 */
settings: Record<string, unknown> | null, };
