// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma ação da frota: a mesma ação de dispositivo em vários equipamentos e,
 * opcionalmente, um cálculo central sobre os resultados.
 */
export type FleetAction = { id: string, title: string, description?: string, icon?: string, 
/**
 * Ação de dispositivo executada em cada membro.
 */
action: string, 
/**
 * Função pura do script, `fn <reduce>(results, settings)`, que recebe o
 * resultado de todos os membros e devolve o consolidado — sem acesso a
 * equipamento. Pode propor `settings_patch` (ajustes por equipamento) que
 * o operador aceita com um clique (ex.: o plano de canais).
 */
reduce?: string, 
/**
 * Títulos das chaves do consolidado (ver [`PluginAction::labels`]).
 */
labels?: { [key in string]: string }, };
