// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compat } from "./Compat";

/**
 * Equipamento que pode entrar na frota.
 */
export type FleetCandidate = { deviceId: number, name: string, ip: string | null, compat: Compat, reasons: Array<string>, };
