// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetCandidate } from "./FleetCandidate";
import type { FleetMember } from "./FleetMember";
import type { PluginBatchView } from "./PluginBatchView";
import type { PluginSummary } from "./PluginSummary";

/**
 * A página de um plugin de frota.
 */
export type FleetView = { plugin: PluginSummary, 
/**
 * Configuração da frota (segredos mascarados).
 */
settings: Record<string, unknown> | null, members: Array<FleetMember>, candidates: Array<FleetCandidate>, batches: Array<PluginBatchView>, };
