// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatrixAction } from "./MatrixAction";

/**
 * Formato antigo da lista da frota — hoje `fleet.list` (ver [`item_list`]).
 * Continua aceito e é convertido na leitura.
 *
 * A grade membros × itens da página da frota (ex.: roteadores × SSIDs).
 */
export type FleetMatrix = { 
/**
 * Lista no resultado da ação de estado (ex.: `networks`).
 */
field: string, 
/**
 * Campo que identifica a coluna (ex.: `ssid`).
 */
key: string, 
/**
 * Campo com o estado da célula (ex.: `state`).
 */
state: string, 
/**
 * Campo com o detalhe mostrado na célula (ex.: `clients`).
 */
detail?: string, 
/**
 * Editar o item da coluna.
 */
edit?: MatrixAction, 
/**
 * Remover o item da coluna.
 */
remove?: MatrixAction, 
/**
 * Como a tela chama a lista e um item ("Redes", "rede").
 */
title?: string, itemName?: string, icon?: string, 
/**
 * Campos do item mostrados no cartão, abaixo do nome.
 */
subtitle?: Array<string>, 
/**
 * Ação de frota do botão "Nova …".
 */
add?: string, };
