// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FleetRunInput = { 
/**
 * Só estes membros; vazio = todos.
 */
deviceIds: Array<number>, params: Record<string, unknown>, confirmWrite: boolean, };
