// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetAction } from "./FleetAction";
import type { FleetMatrix } from "./FleetMatrix";

/**
 * A página da frota.
 */
export type FleetSpec = { title: string, icon?: string, description?: string, 
/**
 * Ação de dispositivo que dá o estado de cada membro (a "visão geral").
 */
statusAction?: string, matrix?: FleetMatrix, actions?: Array<FleetAction>, };
