// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compat } from "./Compat";

/**
 * Equipamento cadastrado fora da frota. O incompatível também vem, com o
 * porquê — escondê-lo deixaria o operador sem saber por que ele não aparece.
 */
export type FleetCandidate = { deviceId: number, name: string, ip: string | null, compat: Compat, reasons: Array<string>, };
