// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de "Verificar sistema".
 */
export type FleetIdentifyInput = { 
/**
 * Só estes; vazio = os da frota e os candidatos ainda em dúvida.
 */
deviceIds: Array<number>, };
