// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FleetRunInput = { 
/**
 * Só estes membros; vazio = todos.
 */
deviceIds: Array<number>, params: Record<string, unknown>, 
/**
 * Parâmetros de um membro, por cima dos comuns.
 */
deviceParams?: Record<number, Record<string, unknown>>, confirmWrite: boolean, };
