// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FunctionalTest = { action: string, params: Record<string, unknown>, 
/**
 * Chaves que o resultado (objeto) precisa ter.
 */
expectKeys?: Array<string>, 
/**
 * Mínimo de linhas quando o resultado é uma lista.
 */
expectMinRows?: number, expectContains?: string, };
