// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDelivery } from "./ArtifactDelivery";
import type { ArtifactSummaryItem } from "./ArtifactSummaryItem";
import type { ArtifactVariant } from "./ArtifactVariant";

export type GeneratedArtifact = { profile: string, 
/**
 * Rótulo amigável do equipamento.
 */
label: string, 
/**
 * Como o usuário deve consumir o artefato.
 */
delivery: ArtifactDelivery, fileName: string, 
/**
 * Dica de linguagem para realce de sintaxe no frontend.
 */
language: string, content: string, instructions: Array<string>, 
/**
 * Perfis móveis podem exibir QR Code.
 */
supportsQrCode: boolean, 
/**
 * Parâmetros do túnel em formato legível — **não** contém a chave privada.
 */
summary: Array<ArtifactSummaryItem>, 
/**
 * Scripts de terminal equivalentes, um por gerenciador de pacotes.
 */
variants: Array<ArtifactVariant>, };
