// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerUsageSummary } from './ContainerUsageSummary'
import type { HostHistoryPoint } from './HostHistoryPoint'
import type { MetricsRange } from './MetricsRange'

export type HostHistoryResponse = {
  hostKey: string
  range: MetricsRange
  stepMinutes: number
  host: Array<HostHistoryPoint>
  containers: Array<ContainerUsageSummary>
}
