// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskUsage } from './DiskUsage'

export type HostHistoryPoint = {
  at: string
  cpuAvg: number
  cpuMax: number
  memoryUsed: number
  memoryTotal: number
  load1: number
  netRxBps: number
  netTxBps: number
  disks: Array<DiskUsage>
}
