// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HourOfDaySummary } from './HourOfDaySummary'
import type { HourlyHeatmapCell } from './HourlyHeatmapCell'
import type { HourlyHeatmapMonitorSummary } from './HourlyHeatmapMonitorSummary'

/**
 * Resposta completa com a matriz de calor horária e indicadores de pico.
 */
export type HourlyHeatmapResponse = {
  matrix: Array<HourlyHeatmapCell>
  byHourOfDay: Array<HourOfDaySummary>
  monitors: Array<HourlyHeatmapMonitorSummary>
  overallAvgLatencyMs: number | null
  peakHour: number | null
  bestHour: number | null
  overallUptimePercentage: number
  totalChecks: number
  startDate: string
  endDate: string
}
