// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HourlyDistributionBin } from './HourlyDistributionBin'
import type { HourlyDistributionTotals } from './HourlyDistributionTotals'

/**
 * Resposta de distribuição horária de eventos.
 */
export type HourlyDistributionResponse = {
  hours: number
  bins: Array<HourlyDistributionBin>
  totals: HourlyDistributionTotals
}
