// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bin horário da distribuição de eventos.
 */
export type HourlyDistributionBin = {
  label: string
  hour: number
  timestamp: string
  critical: number
  warning: number
  info: number
}
