// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Totais agregados da distribuição de eventos.
 */
export type HourlyDistributionTotals = {
  critical: number
  warning: number
  info: number
  total: number
}
