// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resumo agregado por hora do dia (0h..23h) ao longo do período selecionado.
 */
export type HourOfDaySummary = {
  hour: number
  avgLatencyMs: number | null
  minLatencyMs: number | null
  maxLatencyMs: number | null
  uptimePercentage: number
  totalChecks: number
}
