// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Célula individual da matriz de calor horária (Data x Hora).
 */
export type HourlyHeatmapCell = {
  date: string
  dayOfWeek: number
  hour: number
  avgLatencyMs: number | null
  minLatencyMs: number | null
  maxLatencyMs: number | null
  uptimePercentage: number
  totalChecks: number
  upChecks: number
  downChecks: number
}
