// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadados resumidos dos monitores abrangidos pelo heatmap.
 */
export type HourlyHeatmapMonitorSummary = {
  id: number
  name: string
  target: string
  checkType: string
  isSaas: boolean
  saasService: string | null
  currentStatus: string
}
