// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaSuggestion } from "./LayaSuggestion";

export type IdentitySuggestion = { 
/**
 * Um id de `devices::kinds::DEVICE_KINDS`.
 */
deviceType: LayaSuggestion | null, 
/**
 * Um id de `devices::systems::catalog()`.
 */
operatingSystem: LayaSuggestion | null, };
