// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O resultado de `POST /api/devices/identify`.
 *
 * Carrega **a evidência junto com a conclusão** de propósito. Foi a falta disso
 * que deixou um OpenWrt passar por Linux sem ninguém entender por quê: o campo
 * dizia "Linux" e não havia onde conferir que a razão era um `sysDescr` com o
 * `uname` genérico.
 */
export type IdentifyResult = {
  operatingSystem: string
  label: string
  /**
   * `declarado`, `snmp`, `sonda`, `cadastro` ou `padrão`.
   */
  source: string
  reason: string
  /**
   * O que o SNMP respondeu, para a tela poder mostrar o texto cru.
   */
  sysDescr: string | null
  sysObjectId: string | null
  /**
   * A identificação do servidor SSH, quando a porta 22 respondeu.
   */
  sshBanner: string | null
  /**
   * Dados de inventário que o formulário pode preencher sem adivinhar.
   * Nulos quando a sonda/descoberta não trouxe evidência suficiente.
   */
  suggestedVendor: string | null
  suggestedModel: string | null
  /**
   * Nome anunciado pelo próprio equipamento, preferencialmente via
   * `sysName`; a tela só o aplica enquanto o operador não tiver digitado.
   */
  suggestedName: string | null
  /**
   * Forma de acesso deduzida pela mesma regra usada depois do cadastro.
   */
  accessMode: string
  accessModeReason: string
  /**
   * Se alguma evidência ao vivo chegou. Falso significa que a conclusão saiu
   * só do cadastro — e a tela precisa dizer isso em vez de anunciar uma
   * detecção que não aconteceu.
   */
  probed: boolean
}
