// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaSuggestion } from "./LayaSuggestion";
import type { MonitorSuggestion } from "./MonitorSuggestion";

export type InterfaceSuggestions = { 
/**
 * Falso com o Laya desligado, sem a frente liberada ou fora do ar — a
 * tela simplesmente não mostra sugestão.
 */
available: boolean, 
/**
 * `value` é o ifIndex.
 */
uplink: LayaSuggestion | null, monitor: Array<MonitorSuggestion>, model: string | null, };
