// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceCandidate } from "./InterfaceCandidate";

/**
 * `POST /api/snmp/interfaces/suggestions` — vem da tela, sem id: funciona
 * num cadastro que ainda não foi salvo.
 */
export type InterfaceSuggestionsInput = { deviceName: string | null, deviceType: string | null, sysDescr: string | null, interfaces: Array<InterfaceCandidate>, };
