// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma interface como a tela a conhece — do escaneamento SNMP ou do cadastro.
 */
export type InterfaceCandidate = { ifIndex: number, name: string, alias: string | null, descr: string | null, ifType: number | null, 
/**
 * bits/s.
 */
speed: number | null, operUp: boolean | null, inOctets: number | null, outOctets: number | null, };
