// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemAction } from "./ItemAction";
import type { ItemColumn } from "./ItemColumn";
import type { ItemLayout } from "./ItemLayout";

/**
 * A lista de itens de um plugin.
 */
export type ItemList = { 
/**
 * Como a tela chama a lista ("Redes", "Pacotes").
 */
title?: string, 
/**
 * Como chama um item ("rede") — é o "Nova rede" do botão.
 */
itemName?: string, icon?: string, 
/**
 * Ação de leitura que dá a lista (equipamento). Na frota fica vazio: é a
 * `statusAction` de cada membro.
 */
source?: string, 
/**
 * Onde está a lista na saída (`networks`). Vazio: a saída é a lista.
 */
field?: string, 
/**
 * Campo que identifica o item (e aparece em destaque).
 */
key: string, layout: ItemLayout, 
/**
 * Colunas da tabela, na ordem. Vazio: todas as chaves do item.
 */
columns?: Array<ItemColumn>, 
/**
 * Campos mostrados no cartão, abaixo do nome.
 */
subtitle?: Array<string>, 
/**
 * Campo com o estado do item (`up`, `disabled`…), que vira a cor.
 */
state?: string, 
/**
 * Campo numérico somado no cartão (ex.: `clients`).
 */
detail?: string, 
/**
 * Parâmetro da ação de lista que recebe o texto da busca.
 */
searchParam?: string, 
/**
 * Ações sem parâmetro obrigatório, como botões da barra.
 */
toolbar?: Array<string>, 
/**
 * Ação do botão "Nova …".
 */
add?: string, 
/**
 * Aberta ao clicar no item, com o formulário preenchido por ele.
 */
edit?: ItemAction, remove?: ItemAction, 
/**
 * Outras ações sobre o item.
 */
rowActions?: Array<ItemAction>, };
