// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma coluna da lista em tabela, na ordem e com o rótulo da tela.
 */
export type ItemColumn = { key: string, label: string, };
