// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um botão sobre um item ("Editar", "Instalar pacote").
 */
export type ItemAction = { 
/**
 * Ação do plugin (equipamento) ou de frota.
 */
action: string, 
/**
 * Texto do botão. Sem ele, o título da ação.
 */
label?: string, icon?: string, 
/**
 * Parâmetro da ação → campo do item que o preenche.
 */
params: { [key in string]: string }, 
/**
 * Só aparece quando o campo do item é verdadeiro.
 */
showWhen?: string, 
/**
 * Some quando o campo do item é verdadeiro.
 */
hideWhen?: string, };
