// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaModelOption } from './LayaModelOption'

export type LayaModelsResponse = {
  /**
   * O Ollaya respondeu.
   */
  online: boolean
  errorMessage: string | null
  /**
   * Nomes como o Ollaya os lista (`laya:multilingual`…).
   */
  installed: Array<string>
  /**
   * Carregados na memória agora (`/api/ps`). Fora dela, a primeira
   * pergunta espera o modelo sair do disco (5–20 s).
   */
  loaded: Array<string>
  /**
   * Catálogo conhecido mais o que está instalado fora dele.
   */
  options: Array<LayaModelOption>
}
