// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quão provável o Laya acha que um grupo de ferramentas é necessário.
 */
export type LayaGroupScore = {
  id: string
  purpose: string
  /**
   * 0–1.
   */
  probability: number
  /**
   * Passou do limiar configurado: iria para a IA.
   */
  selected: boolean
}
