// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Triagem da IA proativa: o Laya decide se um alerta merece resumo do LLM.
 */
export type LayaTriageMode = 'off' | 'shadow' | 'enforce'
