// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaTriageMode } from './LayaTriageMode'

/**
 * A opinião gravada no alerta. Percentuais 0–100.
 */
export type LayaTriage = {
  actionable: number
  symptom: number
  transient: number
  model: string
  mode: LayaTriageMode
  /**
   * O resumo automático não saiu por causa desta opinião.
   */
  suppressed: boolean
  assessedAt: string
}
