// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayaSuggestion = { value: string, 
/**
 * 0–100, uma casa decimal.
 */
confidence: number, 
/**
 * O modelo que respondeu (`laya:multilingual`…).
 */
model: string, };
