// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaTriageMode } from "./LayaTriageMode";

/**
 * Onde o Laya é consultado. Cada frente só sugere; nenhuma muda dado sozinha.
 */
export type LayaFeatures = { 
/**
 * Escolher os grupos de ferramentas de cada pergunta do chat.
 */
chatTools: boolean, 
/**
 * Sugerir tipo e sistema dos dispositivos encontrados na descoberta.
 */
deviceIdentity: boolean, 
/**
 * Sugerir o uplink e as interfaces que valem monitorar.
 */
interfaces: boolean, 
/**
 * Classificar cada padrão novo de log (falha de login, link, reboot…).
 */
logEvents: boolean, incidentTriage: LayaTriageMode, };
