// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiLayaSettings } from './AiLayaSettings'

/**
 * Baixa o modelo do Laya no Ollaya do formulário.
 */
export type LayaPullInput = { laya: AiLayaSettings }
