// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um modelo que a tela oferece no autocomplete.
 */
export type LayaModelOption = {
  name: string
  /**
   * Só os do catálogo têm; um instalado por fora vem sem.
   */
  description: string | null
  installed: boolean
}
