// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogIngestMetrics = { received: number, stored: number, droppedQueueFull: number, droppedRateLimit: number, droppedUnknownSource: number, droppedOversized: number, };
