// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que o servidor sabe sobre o mascaramento da origem.
 */
export type LogNatDiagnostics = {
  /**
   * Quantas origens chegam com o endereço reescrito.
   */
  maskedCount: number
  /**
   * Dessas, quantas ainda **não** estão vinculadas a um dispositivo.
   *
   * É este número, e não o de cima, que decide se o aviso aparece. O
   * mascaramento continua existindo depois de tudo vinculado — mas aí ele
   * deixou de atrapalhar, e um aviso permanente sobre um problema resolvido
   * treina o operador a ignorar avisos.
   */
  unresolvedMaskedCount: number
  /**
   * Se o processo está dentro de um container — muda o texto da orientação,
   * não o comportamento.
   */
  containerized: boolean
  /**
   * Os endereços reconhecidos como gateway, para o aviso poder nomeá-los.
   */
  gateways: Array<string>
}
