// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que o servidor sabe sobre o mascaramento da origem.
 */
export type LogNatDiagnostics = {
  /**
   * Quantas origens chegam com o endereço reescrito.
   */
  maskedCount: number
  /**
   * Se o processo está dentro de um container — muda o texto da orientação,
   * não o comportamento.
   */
  containerized: boolean
  /**
   * Os endereços reconhecidos como gateway, para o aviso poder nomeá-los.
   */
  gateways: Array<string>
}
