// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntry } from "./LogEntry";
import type { LogPageMeta } from "./LogPageMeta";
import type { LogTemplateInfo } from "./LogTemplateInfo";

export type LogPageResponse = { data: Array<LogEntry>, meta: LogPageMeta, 
/**
 * Os padrões das linhas desta página, com a categoria de cada um.
 */
templates: Array<LogTemplateInfo>, };
