// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O `meta` do envelope por cursor.
 */
export type LogPageMeta = {
  /**
   * Cursor da próxima página. `null` quando acabou — é este campo, e não uma
   * contagem, que encerra a rolagem infinita.
   */
  nextCursor: string | null
  hasMore: boolean
  limit: number
  /**
   * A janela efetivamente consultada, depois de aplicados o padrão de 24 h e
   * o teto de 7 dias. A tela mostra isto para o usuário não achar que está
   * vendo o período inteiro que pediu.
   */
  from: string
  to: string
}
