// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogIngestMetrics } from './LogIngestMetrics'
import type { LogSourceEntry } from './LogSourceEntry'

export type LogSourcesResponse = {
  data: Array<LogSourceEntry>
  /**
   * Quantas origens estão descartando mensagem agora. É o número do banner
   * da tela — sem ele, a regra "fonte desconhecida não grava" vira um buraco
   * negro de suporte.
   */
  unknownCount: number
  /**
   * Contadores de ingestão desde o boot.
   */
  metrics: LogIngestMetrics
}
