// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma origem vista pelo servidor desde o último reinício.
 */
export type LogSourceEntry = {
  sourceIp: string
  /**
   * `device` | `network` | `ambiguous` | `unknown`.
   */
  kind: string
  deviceId: number | null
  deviceName: string | null
  /**
   * Candidatos quando o mesmo IP existe em mais de um dispositivo. É o que a
   * tela oferece no vínculo manual.
   */
  candidates: Array<{ id: number; name: string }>
  hostname: string | null
  messageCount: number
  /**
   * Quantas foram descartadas por não resolver para nada cadastrado.
   */
  droppedCount: number
  firstSeenAt: string
  lastSeenAt: string
  lastMessage: string
}
