// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de `PUT /api/logs/templates/{hash}`.
 */
export type LogTemplateUpdate = { category: string }
