// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `meta` do envelope do Lucid.
 *
 * O frontend usa `total`, `currentPage` e `lastPage`. Os demais campos são
 * emitidos por compatibilidade defensiva: telas antigas e integrações externas
 * podem ler as URLs, e omiti-las produziria `undefined` silencioso.
 */
export type LucidMeta = { total: number, perPage: number, currentPage: number, lastPage: number, firstPage: number, firstPageUrl: string, lastPageUrl: string, nextPageUrl: string | null, previousPageUrl: string | null, };
