// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LucidMeta } from "./LucidMeta";

/**
 * `{ data, meta }` — o corpo que o `useInfiniteList` espera.
 */
export type LucidPage<T> = { data: Array<T>, meta: LucidMeta, };
