// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MaintenanceWindowResponse = {
  id: number
  siteId: number | null
  deviceId: number | null
  name: string
  description: string | null
  startsAt: string
  endsAt: string
  createdBy: number | null
  createdAt: string
  updatedAt: string
}
