// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Com que equipamentos o plugin diz ser compatível. Todos os campos são
 * opcionais e valem juntos (E).
 */
export type MatchRule = { 
/**
 * Ids do catálogo de sistemas (`openwrt`, `routeros`, `linux`, …).
 */
platforms?: Array<string>, vendorRegex?: string, modelRegex?: string, 
/**
 * Restrição de firmware (`>=21.02, <24`).
 */
firmware?: string, 
/**
 * Regex sobre o título/`Server` da página web — pista para o
 * reconhecimento de equipamento que só tem interface HTTP.
 */
httpFingerprint?: string, };
