// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma ação da frota disparada a partir de um item da grade (ex.: editar o
 * SSID da coluna): o formulário vem preenchido com campos do item e os
 * equipamentos que o têm já marcados.
 */
export type MatrixAction = { 
/**
 * Ação de frota (`fleet.actions[].id`).
 */
action: string, 
/**
 * Parâmetro da ação → campo do item.
 */
params: { [key in string]: string }, };
