// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progresso do download de um modelo num servidor local (Ollama ou Ollaya).
 */
export type ModelPullProgress = { status: string, digest: string | null, total: number | null, completed: number | null, percentage: number | null, done: boolean, error: string | null, };
