// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorTimeSeriesPoint } from './MonitorTimeSeriesPoint'

/**
 * Resposta completa do endpoint de série temporal.
 */
export type MonitorTimeSeriesResponse = {
  timeframe: string
  samples: Array<MonitorTimeSeriesPoint>
  avgLatency: number
  maxLatency: number
  minLatency: number
  packetLossPct: number
  totalChecks: number
}
