// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estatísticas agregadas exibidas no detalhe de um monitor.
 */
export type MonitorStats = { avgLatency: number | null, minLatency: number | null, maxLatency: number | null, lastLatency: number | null, uptimePercentage: number, totalChecks: number, upChecks: number, };
