// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item de detalhe de monitor em uma amostra temporal.
 */
export type MonitorTimeSeriesDetailItem = {
  id: number
  name: string
  target: string
  type: string
  deviceName: string | null
  status: string
  latencyMs: number | null
  lossPct: number
}
