// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorTimeSeriesDetailItem } from './MonitorTimeSeriesDetailItem'

/**
 * Ponto da série temporal de latência.
 */
export type MonitorTimeSeriesPoint = {
  time: string
  timestamp: number
  latency: number
  loss: number
  monitorsDetail: Array<MonitorTimeSeriesDetailItem>
}
