// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de uma execução manual de monitor (ping, tcp, http, dns, etc.).
 */
export type MonitorRunResponse = { message: string; result: any }
