// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de uptime de um monitor em uma janela de horas.
 */
export type MonitorUptimeResponse = { monitorId: number, hours: number, uptimePercentage: number, totalChecks: number, upChecks: number, downChecks: number, unknownChecks: number, avgLatencyMs: number | null, };
