// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OllamaModelItem = {
  name: string
  size: bigint | null
  parameterSize: string | null
  modifiedAt: string | null
}
