// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OllamaModelItem } from "./OllamaModelItem";
import type { OllamaRecommendedModel } from "./OllamaRecommendedModel";

export type OllamaModelsResponse = { installed: Array<OllamaModelItem>, recommended: Array<OllamaRecommendedModel>, isOnline: boolean, errorMessage: string | null, };
