// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OllamaRecommendedModel = { name: string, description: string, parameterSize: string, isInstalled: boolean, toolCallingOptimized: boolean, };
