// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OllamaPullProgress = {
  status: string
  digest: string | null
  total: bigint | null
  completed: bigint | null
  percentage: number | null
  done: boolean
  error: string | null
}
