// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de status para o assistente de configuração.
 */
export type OnboardingStatus = { completed: boolean, completedAt: string | null, needsOnboarding: boolean, sitesCount: number, networksCount: number, dnsServersCount: number, vpnConfigured: boolean, detectedLanIp: string | null, detectedPublicIp: string | null, };
