// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenCodeModelItem } from "./OpenCodeModelItem";

export type OpenCodeModelsResponse = { models: Array<OpenCodeModelItem>, isOnline: boolean, errorMessage: string | null, };
