// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenCodeModelItem = { id: string, isFree: boolean, description?: string | null, name?: string | null, supportsTools?: boolean | null, };
