// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenRouterModelItem } from './OpenRouterModelItem'

export type OpenRouterModelsResponse = {
  models: Array<OpenRouterModelItem>
  isOnline: boolean
  errorMessage: string | null
}
