// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que a tela recebe para montar o seletor.
 */
export type OperatingSystemOption = {
  id: string
  label: string
  icon: string
  /**
   * Se a ativação automática de log tem comandos para este sistema. Sem
   * isto a tela ofereceria uma ação que não tem como funcionar.
   */
  supportsSyslog: boolean
  supportsMacTelnet: boolean
  /**
   * Perfil equivalente no assistente da VPN, quando existe.
   */
  vpnProfile: string | null
}
