// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Como a tela apresenta o resultado de uma ação.
 */
export type OutputKind = "text" | "table" | "kv" | "json";
