// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Como a tela escreve o valor de uma chave da saída — com os formatadores do
 * sistema, para um plugin mostrar bytes, latência e datas como o resto da
 * interface mostra.
 */
export type OutputFormat = "bytes" | "bps" | "latency" | "percent" | "duration" | "uptime" | "datetime" | "relative" | "count" | "state";
