// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationMeta } from './PaginationMeta'

/**
 * `{ data, meta }` — o corpo que o `useInfiniteList` espera.
 */
export type PaginatedResponse<T> = { data: Array<T>; meta: PaginationMeta }
