// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma ação oferecida sobre a linha selecionada do painel ("Instalar pacote").
 */
export type PanelRowAction = { 
/**
 * Id da ação do manifesto.
 */
action: string, label: string, icon?: string, 
/**
 * Parâmetro da ação → coluna da linha que o preenche.
 */
params: { [key in string]: string }, 
/**
 * Só aparece quando a coluna é verdadeira.
 */
showWhen?: string, 
/**
 * Some quando a coluna é verdadeira.
 */
hideWhen?: string, };
