// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerHints = {
  /**
   * Túnel ativo, mas o ping falha: provável firewall bloqueando na interface WG.
   */
  needsFirewallHint: boolean
  /**
   * Túnel ativo e ping falhando, mas o monitor **não** roda no `vpn-probe`: o
   * ICMP sai da máquina da API, que não tem rota para dentro do túnel. O
   * pacote nem chega ao equipamento — acusar o firewall dele seria
   * diagnóstico falso.
   */
  pingOutsideTunnel: boolean
  /**
   * Monitor de ping provisionado automaticamente para o peer — usado para
   * navegar ao histórico de conectividade.
   */
  pingMonitorId: number | null
}
