// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatEntry } from "./CompatEntry";
import type { PluginManifest } from "./PluginManifest";
import type { PluginTests } from "./PluginTests";

export type PluginPackage = { format: number, manifest: PluginManifest, script: string, usage: string, compatibility: Array<CompatEntry>, tests: PluginTests, };
