// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionalTest } from "./FunctionalTest";
import type { UnitTest } from "./UnitTest";

export type PluginTests = { unit: Array<UnitTest>, functional: Array<FunctionalTest>, };
