// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { OutputKind } from "./OutputKind";

/**
 * Uma operação que o plugin oferece.
 */
export type PluginAction = { 
/**
 * Nome da função no script (`fn <id>(device, params)`).
 */
id: string, title: string, description?: string, effect: Effect, 
/**
 * Esquema JSON (subconjunto — ver [`params`]) dos parâmetros.
 */
params?: Record<string, unknown>, output: OutputKind, 
/**
 * Ação de escrita idempotente, que pode entrar no teste funcional.
 */
safeToRetest: boolean, };
