// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um aplicativo (plugin de frota) para o menu.
 */
export type PluginApp = { id: number, slug: string, title: string, icon: string, description: string | null, members: number, };
