// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginPackage } from "./PluginPackage";

export type PluginSaveInput = { package: PluginPackage, 
/**
 * Grava como exclusivo deste equipamento.
 */
deviceId?: number | null, };
