// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetSpec } from "./FleetSpec";
import type { MatchRule } from "./MatchRule";
import type { PluginAction } from "./PluginAction";
import type { PluginPanel } from "./PluginPanel";
import type { SettingsSpec } from "./SettingsSpec";
import type { Severity } from "./Severity";
import type { Surface } from "./Surface";
import type { TransportKind } from "./TransportKind";

/**
 * Um plugin na listagem — sem script nem testes.
 */
export type PluginSummary = { id: number, slug: string, name: string, version: string, description: string | null, 
/**
 * `model` (todo equipamento compatível) ou `device` (exclusivo).
 */
scope: string, deviceId: number | null, 
/**
 * `builtin`, `user`, `ai` ou `imported`.
 */
source: string, 
/**
 * `quarantine`, `draft`, `tested`, `active` ou `disabled`.
 */
status: string, transports: Array<TransportKind>, actions: Array<PluginAction>, matcher: MatchRule, 
/**
 * Tela própria do plugin instalado, quando ele declara uma.
 */
panel: PluginPanel | null, 
/**
 * Onde aparece: aba do equipamento, página da frota (Aplicativos).
 */
surfaces: Array<Surface>, 
/**
 * Esquemas da configuração guardada.
 */
settings: SettingsSpec | null, fleet: FleetSpec | null, 
/**
 * Risco da última revisão de segurança.
 */
risk: Severity | null, lastTestAt: string | null, lastTestOk: boolean | null, 
/**
 * Equipamentos em que já passou no teste funcional.
 */
validatedCount: number, updatedAt: string, };
