// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelColumn } from "./PanelColumn";
import type { PanelRowAction } from "./PanelRowAction";

/**
 * Formato antigo da tela do plugin instalado — hoje uma [`ItemList`] em
 * tabela (ver [`item_list`]). Continua aceito e é convertido na leitura.
 *
 * A tela própria do plugin instalado: uma lista vinda de uma ação de leitura
 * (com busca opcional), ações sobre a linha escolhida e botões de barra.
 *
 * É declarativo de propósito: o plugin descreve a tela e a interface a
 * desenha — nenhum código do plugin roda no navegador.
 */
export type PluginPanel = { title: string, icon?: string, 
/**
 * Ação de leitura com `output: table` que preenche a lista.
 */
listAction: string, 
/**
 * Parâmetro da ação de lista que recebe o texto da busca.
 */
searchParam?: string, 
/**
 * Coluna que identifica a linha (e aparece em destaque).
 */
keyColumn: string, 
/**
 * Colunas mostradas, na ordem. Vazio: todas as chaves da linha.
 */
columns?: Array<PanelColumn>, 
/**
 * Ações sem parâmetro da linha, como botões da barra ("Atualizar lista").
 */
toolbar?: Array<string>, rowActions?: Array<PanelRowAction>, };
