// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemList } from "./ItemList";
import type { TestReport } from "./TestReport";

/**
 * A prévia do editor: os testes rodados (as saídas viram a tela simulada) e
 * as listas como a tela as desenha, já convertidas do formato antigo.
 */
export type PluginPreview = { report: TestReport, 
/**
 * A lista da aba do equipamento.
 */
list: ItemList | null, 
/**
 * A lista da página da frota.
 */
fleetList: ItemList | null, };
