// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetSpec } from "./FleetSpec";
import type { ItemList } from "./ItemList";
import type { MatchRule } from "./MatchRule";
import type { PluginAction } from "./PluginAction";
import type { PluginPanel } from "./PluginPanel";
import type { SettingsSpec } from "./SettingsSpec";
import type { Surface } from "./Surface";
import type { TransportKind } from "./TransportKind";

export type PluginManifest = { slug: string, name: string, version: string, description?: string, author?: string, transports: Array<TransportKind>, match: MatchRule, actions: Array<PluginAction>, 
/**
 * Formato antigo de `list`.
 */
panel?: PluginPanel, 
/**
 * Tela própria do plugin instalado: a lista de itens. Sem ela, a aba
 * mostra as ações.
 */
list?: ItemList, 
/**
 * Onde aparece: aba do equipamento, página da frota, ou as duas.
 */
surfaces: Array<Surface>, settings?: SettingsSpec, fleet?: FleetSpec, 
/**
 * Plugins cujas ações este chama (`device.use_plugin`) — reaproveitar em
 * vez de copiar. Precisam estar ativos.
 */
uses?: Array<string>, };
