// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchRule } from "./MatchRule";
import type { PluginAction } from "./PluginAction";
import type { PluginPanel } from "./PluginPanel";
import type { TransportKind } from "./TransportKind";

export type PluginManifest = { slug: string, name: string, version: string, description?: string, author?: string, transports: Array<TransportKind>, match: MatchRule, actions: Array<PluginAction>, 
/**
 * Tela própria do plugin instalado. Sem ela, a aba mostra as ações.
 */
panel?: PluginPanel, };
