// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { OutputFormat } from "./OutputFormat";
import type { OutputKind } from "./OutputKind";

/**
 * Uma operação que o plugin oferece.
 */
export type PluginAction = { 
/**
 * Nome da função no script (`fn <id>(device, params)`).
 */
id: string, title: string, description?: string, effect: Effect, 
/**
 * Esquema JSON (subconjunto — ver [`params`]) dos parâmetros.
 */
params?: Record<string, unknown>, output: OutputKind, 
/**
 * Ação de escrita idempotente, que pode entrar no teste funcional.
 */
safeToRetest: boolean, 
/**
 * Títulos das chaves da saída na tela (`clients` → "Clientes"). A chave
 * continua o contrato com o script; o título é só apresentação.
 */
labels?: { [key in string]: string }, 
/**
 * Como a tela escreve o valor de cada chave (`rx_bytes` → bytes).
 */
formats?: { [key in string]: OutputFormat }, 
/**
 * Ordem das chaves na tela (colunas e campos). O JSON da saída chega com
 * as chaves em ordem alfabética; sem isto, "Canal sugerido" viria antes de
 * "Canal atual". Chave fora da lista vai para o fim.
 */
order?: Array<string>, };
