// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchDevice } from "./BatchDevice";

/**
 * Uma ação de frota em andamento ou concluída.
 */
export type PluginBatchView = { id: number, pluginId: number, action: string, title: string, 
/**
 * `running`, `succeeded`, `partial`, `failed` ou `cancelled`.
 */
status: string, devices: Array<BatchDevice>, 
/**
 * O consolidado da função `reduce`, quando a ação tem uma.
 */
result: unknown, 
/**
 * O consolidado propõe ajustes por equipamento ainda não aplicados.
 */
hasPatch: boolean, error: string | null, createdAt: string, finishedAt: string | null, };
