// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginPackage } from "./PluginPackage";
import type { PluginSummary } from "./PluginSummary";
import type { ReviewReport } from "./ReviewReport";

/**
 * O plugin inteiro, para o editor.
 */
export type PluginDetail = { summary: PluginSummary, package: PluginPackage, review: ReviewReport | null, };
