// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptEntry } from "./TranscriptEntry";

export type PluginRunView = { id: number, pluginId: number | null, pluginName: string | null, deviceId: number, action: string, 
/**
 * `user`, `ai` ou `validation`.
 */
origin: string, 
/**
 * `running`, `succeeded`, `failed` ou `cancelled`.
 */
status: string, params: unknown, output: unknown, transcript: Array<TranscriptEntry>, error: string | null, createdAt: string, finishedAt: string | null, };
