// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginPackage } from "./PluginPackage";

/**
 * Um pacote para a prévia do editor — nada é gravado.
 */
export type PluginPreviewInput = { package: PluginPackage, };
