// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightLevel } from "./PreflightLevel";
import type { PreflightStatus } from "./PreflightStatus";

export type PreflightResult = { status: PreflightStatus, level: PreflightLevel, message: string, recommendation: string, publicIp: string | null, resolvedIp: string | null, port: number, isCgnat: boolean, behindNat: boolean, 
/**
 * Falso quando não houve confirmação externa real da porta UDP.
 */
verified: boolean, };
