// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreflightStatus = 'reachable' | 'port_forward_required' | 'cgnat' | 'unknown'
