// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que a tela usa para se preencher antes de perguntar qualquer coisa.
 */
export type ProvisionHintsResponse = {
  /**
   * Endereço deste servidor que o equipamento deve usar. `null` quando não
   * há resposta confiável — aí a tela exige que o operador digite.
   */
  serverAddress: string | null
  /**
   * De onde veio o palpite, para a tela não apresentar chute como certeza.
   */
  serverAddressSource: string
  serverPort: number
  vendor: string
  vendorSource: string
  /**
   * Porta 22 respondeu à sondagem.
   */
  sshOpen: boolean
  /**
   * Porta 23 respondeu à sondagem.
   */
  telnetOpen: boolean
  macAddress: string | null
  /**
   * Se este processo alcança a camada 2 da rede do equipamento. Falso num
   * container em rede bridge, onde o MAC-Telnet não tem como funcionar.
   */
  layer2Reachable: boolean
}
