// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Onde a restauração escreve.
 */
export type RestoreMode = "new_database" | "replace";
