// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O segredo revelado — só nesta resposta, nunca gravado nem publicado.
 */
export type RevealResult = { output: Record<string, unknown>, };
