// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O formulário de onde a ação que revela tira os parâmetros (o nome da rede…).
 */
export type RevealInput = { params: Record<string, unknown>, };
