// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewAcceptInput = { 
/**
 * O operador declara ter lido os riscos (exigido em risco alto e sem IA).
 */
acknowledgeRisk: boolean, };
