// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiReview } from "./AiReview";
import type { Finding } from "./Finding";
import type { Severity } from "./Severity";

export type ReviewReport = { risk: Severity, findings: Array<Finding>, ai?: AiReview, 
/**
 * Por que a IA não revisou (desligada, sem resposta, resposta inválida).
 */
aiError?: string, reviewedAt: string, 
/**
 * Checksum do pacote revisado — a revisão só vale para este código.
 */
checksum: string, };
