// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunActionInput = { params: Record<string, unknown>, 
/**
 * Confirmação explícita para ação que altera o equipamento.
 */
confirmWrite: boolean, };
