// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Limites sugeridos de latência e perda de pacotes para o serviço SaaS.
 */
export type SaasThresholds = {
  warningLatencyMs: number
  criticalLatencyMs: number
  maxPacketLossPercent: number | null
}
