// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaasPreset } from './SaasPreset'

/**
 * Resposta da listagem de presets SaaS.
 */
export type SaasPresetsResponse = {
  presets: Array<SaasPreset>
  totalPresets: number
  provisionedCount: number
}
