// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaasThresholds } from './SaasThresholds'

/**
 * Item do catálogo de serviços SaaS pré-configurados.
 */
export type SaasPreset = {
  id: string
  name: string
  provider: string
  category: string
  icon: string
  color: string
  description: string
  checkType: string
  target: string
  port: bigint | null
  httpMethod: string | null
  acceptedStatusCodes: Array<number> | null
  intervalSeconds: number
  timeoutSeconds: number
  suggestedThresholds: SaasThresholds
  isProvisioned: boolean
  monitorId: bigint | null
  currentStatus: string | null
  currentLatencyMs: number | null
}
