// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta do provisionamento de serviços SaaS.
 */
export type SaasProvisionResponse = {
  provisionedCount: number
  createdMonitorIds: Array<bigint>
  existingMonitorIds: Array<bigint>
  message: string
}
