// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requisição de provisionamento de serviços SaaS em lote ou individual.
 */
export type SaasProvisionRequest = {
  presetIds: Array<string>
  intervalSeconds: number | null
  timeoutSeconds: number | null
}
