// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de `GET /` (§5.6). Fora do prefixo `/api` e sem autenticação —
 * é o health check que o docker-compose usa.
 */
export type ServiceInfo = { status: string, service: string, version: string, };
