// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerAddressEntry } from './ServerAddressEntry'

export type ServerAddressesResponse = {
  data: Array<ServerAddressEntry>
  /**
   * Qual usar quando nada indicar outro.
   */
  preferredId: string | null
}
