// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuração que o plugin guarda: o estado desejado.
 *
 * `fleet` vale para todos os equipamentos onde o plugin está instalado (ex.:
 * os SSIDs da rede); `device` é o ajuste de um equipamento (ex.: o canal
 * daquele rádio). O script recebe as duas em `device.settings`.
 */
export type SettingsSpec = { fleet?: Record<string, unknown>, device?: Record<string, unknown>, };
