// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupSnippet } from "./SetupSnippet";

export type SetupGuide = { 
/**
 * Endereço que o operador deve apontar. Vazio quando o servidor não
 * conseguiu descobrir o próprio IP — a tela então pede que ele digite.
 */
serverAddress: string, port: number, snippets: Array<SetupSnippet>, };
