// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupSnippet = { 
/**
 * Chave do catálogo de sistemas, para a tela escolher ícone e ordenar.
 */
system: string, label: string, 
/**
 * O que o operador precisa saber antes de colar.
 */
note: string, commands: string, };
