// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpConfig = { host: string, port?: number, username: string, password?: string, privateKey?: string, passphrase?: string, basePath?: string, 
/**
 * Impressão digital (SHA-256) da chave do servidor, gravada na primeira
 * conexão bem-sucedida. Dali em diante uma chave diferente é recusada: é
 * o que impede um intermediário de receber o backup no lugar do NAS.
 */
hostKeyFingerprint?: string, };
