// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Referência compacta a um site.
 */
export type SiteRef = { id: number | null, name: string, };
