// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageObjectResponse } from "./StorageObjectResponse";

/**
 * Uma página do explorador.
 */
export type StorageBrowseResponse = { path: string, objects: Array<StorageObjectResponse>, nextCursor: string | null, };
