// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageProvider } from "./StorageProvider";

/**
 * Uma linha da lista.
 */
export type StorageDestinationResponse = { id: number, name: string, provider: StorageProvider, 
/**
 * Para onde vão os arquivos, num texto só: `s3://bucket/prefixo`,
 * `backup@nas:22/srv/copias`. Nulo quando a credencial não decifra.
 */
target: string | null, createdAt: string, updatedAt: string, };
