// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma cópia de backup guardada no destino.
 */
export type StorageBackupResponse = { key: string, name: string, size: number | null, lastModified: string | null, };
