// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageConfig } from "./StorageConfig";
import type { StorageProvider } from "./StorageProvider";

/**
 * "Testar conexão" do formulário, antes de salvar. Com `id`, os segredos em
 * branco vêm do cadastro.
 */
export type StorageTestInput = { id?: number | null, provider: StorageProvider, config: StorageConfig, };
