// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageConfig } from "./StorageConfig";
import type { StorageProvider } from "./StorageProvider";

/**
 * O cadastro para o formulário de edição.
 */
export type StorageDestinationDetail = { 
/**
 * A config sem os segredos.
 */
config: StorageConfig, 
/**
 * Segredos que estão gravados (`password`, `secretAccessKey`…).
 */
secretsSet: Array<string>, id: number, name: string, provider: StorageProvider, 
/**
 * Para onde vão os arquivos, num texto só: `s3://bucket/prefixo`,
 * `backup@nas:22/srv/copias`. Nulo quando a credencial não decifra.
 */
target: string | null, backupEnabled: boolean, backupIntervalHours: number, backupRetention: number, lastBackupAt: string | null, 
/**
 * `success` | `failed`.
 */
lastBackupStatus: string | null, lastBackupError: string | null, nextBackupAt: string | null, createdAt: string, updatedAt: string, };
