// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma cópia de backup do destino (prévia e restauração).
 */
export type StorageBackupKeyInput = { key: string, };
