// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageProvider = "local" | "aws_s3" | "minio" | "cloudflare_r2" | "s3_compatible" | "google_gcs" | "azure_blob" | "sftp";
