// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBackupResponse } from "./StorageBackupResponse";

/**
 * Resultado de "Fazer backup agora".
 */
export type StorageBackupRunResponse = { backup: StorageBackupResponse, 
/**
 * Cópias antigas apagadas pela retenção.
 */
pruned: number, };
