// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Informação que o formulário precisa e que não é de nenhum destino.
 */
export type StoragesMetaResponse = { 
/**
 * Pasta do servidor sob a qual ficam os armazenamentos locais.
 */
localRoot: string, };
