// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um item do explorador.
 */
export type StorageObjectResponse = { key: string, name: string, size: number | null, lastModified: string | null, isDirectory: boolean, };
