// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageConfig } from "./StorageConfig";
import type { StorageProvider } from "./StorageProvider";

/**
 * Formulário de criação e edição. Na edição, segredo em branco mantém o
 * gravado.
 */
export type StorageDestinationInput = { name: string, provider: StorageProvider, config: StorageConfig, backupEnabled: boolean, backupIntervalHours: number, backupRetention: number, };
