// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AzureConfig } from "./AzureConfig";
import type { GcsConfig } from "./GcsConfig";
import type { LocalConfig } from "./LocalConfig";
import type { S3Config } from "./S3Config";
import type { SftpConfig } from "./SftpConfig";

/**
 * Config de um destino, discriminada por `type`.
 *
 * `deny_unknown_fields` fica **de fora** de propósito: o `projectId` do GCS é
 * só informativo, e recusar a config inteira por causa de um campo extra
 * tornaria ilegível o que já está gravado.
 */
export type StorageConfig = { "type": "local" } & LocalConfig | { "type": "s3" } & S3Config | { "type": "gcs" } & GcsConfig | { "type": "azure_blob" } & AzureConfig | { "type": "sftp" } & SftpConfig;
