// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma cópia da configuração guardada num destino.
 */
export type SystemBackupCopyResponse = { key: string, name: string, size: number | null, lastModified: string | null, };
