// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemBackupCopyResponse } from "./SystemBackupCopyResponse";

/**
 * Resultado de "Fazer backup agora".
 */
export type SystemBackupRunResponse = { copy: SystemBackupCopyResponse, storageDestinationName: string, 
/**
 * Cópias antigas apagadas pela retenção.
 */
pruned: number, };
