// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma cópia guardada num destino (prévia e restauração).
 */
export type SystemBackupCopyInput = { storageDestinationId: number, key: string, };
