// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O plano de backup do sistema, como a tela o mostra.
 */
export type SystemBackupPlanResponse = { storageDestinationId: number | null, storageDestinationName: string | null, backupEnabled: boolean, backupIntervalHours: number, backupRetention: number, lastBackupAt: string | null, 
/**
 * `success` | `failed`.
 */
lastBackupStatus: string | null, lastBackupError: string | null, nextBackupAt: string | null, 
/**
 * Há uma cópia em andamento agora.
 */
running: boolean, };
