// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O plano: para onde, de quanto em quanto tempo, quantas manter.
 */
export type SystemBackupPlanInput = { storageDestinationId: number | null, backupEnabled: boolean, backupIntervalHours: number, backupRetention: number, };
