// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestConnectionResponse = {
  success: boolean
  latencyMs: number
  message: string
  model: string | null
}
