// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestCaseResult } from "./TestCaseResult";
import type { UxHint } from "./UxHint";

export type TestReport = { passed: boolean, total: number, failed: number, 
/**
 * Problemas de validação do pacote. Qualquer um reprova.
 */
problems: Array<string>, cases: Array<TestCaseResult>, 
/**
 * Sugestões de usabilidade da tela ([`ux_lint`]). Não reprovam.
 */
hints: Array<UxHint>, };
