// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiLayaSettings } from "./AiLayaSettings";

/**
 * Testa o Laya com o que está no formulário, ainda não salvo.
 */
export type TestLayaInput = { laya: AiLayaSettings, 
/**
 * Pergunta de exemplo; sem ela, vale a padrão do servidor.
 */
question: string | null, };
