// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptEntry } from "./TranscriptEntry";

export type TestCaseResult = { name: string, action: string, passed: boolean, message?: string, output?: unknown, transcript: Array<TranscriptEntry>, };
