// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayaGroupScore } from './LayaGroupScore'

export type TestLayaResponse = {
  success: boolean
  /**
   * O Ollaya respondeu.
   */
  online: boolean
  /**
   * O modelo configurado está instalado nele.
   */
  modelInstalled: boolean
  latencyMs: number
  message: string
  /**
   * Quem respondeu de fato (`laya:en`, `laya:multilingual`…).
   */
  model: string | null
  groups: Array<LayaGroupScore>
}
