// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";

/**
 * Uma linha do registro da execução.
 */
export type TranscriptEntry = { seq: number, 
/**
 * `ssh`, `http`, `telnet`, `log`, `denied` ou `error`.
 */
kind: string, request: string, effect?: Effect, 
/**
 * Código de saída (SSH) ou status HTTP.
 */
status?: number, output: string, durationMs: number, origin: string, at: string, };
