// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fixture } from "./Fixture";

export type UnitTest = { name?: string, action: string, params: Record<string, unknown>, fixtures: Array<Fixture>, 
/**
 * Subconjunto esperado do resultado (objetos comparados por chave).
 */
expect?: unknown, 
/**
 * Texto que precisa aparecer no resultado serializado.
 */
expectContains?: string, 
/**
 * A ação precisa falhar com uma mensagem que contenha este texto.
 */
expectError?: string, 
/**
 * Firmware do equipamento simulado (`device.info.firmware`). Permite
 * testar o caminho que depende da versão — ex.: opkg × apk no OpenWrt.
 */
firmware?: string, };
