// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma sugestão: onde (`action.encryption`) e o que fazer.
 */
export type UxHint = { at: string, message: string, };
