// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de `POST /api/vpn/peers/:id/firewall-hints`.
 */
export type VpnFirewallHintsResponse = {
  profile: string
  label: string
  content: string
  message: string
}
