// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerializedVpnArtifact } from './SerializedVpnArtifact'
import type { VpnPeerResponse } from './VpnPeerResponse'

/**
 * Resposta de `POST /api/vpn/peers/:id/rotate`.
 */
export type VpnKeyRotationResponse = {
  message: string
  peer: VpnPeerResponse
  artifact: SerializedVpnArtifact
}
