// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VpnPeerConnectionStatus } from "./VpnPeerConnectionStatus";
import type { VpnPeerDeviceView } from "./VpnPeerDeviceView";

/**
 * Corpo de `PATCH /api/vpn/peers/:id` — peer + dispositivo renomeado.
 *
 * Sem os avisos de diagnóstico: quem os calcula é a listagem, e acrescentá-los
 * aqui mudaria a resposta que o backend AdonisJS devolve (§16, paridade).
 */
export type VpnPeerWithDevice = { device: VpnPeerDeviceView | null, id: number, vpnServerId: number, deviceId: number, publicKey: string, deviceProfile: string, persistentKeepalive: number, lastHandshakeAt: string | null, 
/**
 * Último keepalive contabilizado — é o sinal de vida que sustenta o status.
 */
lastSeenAt: string | null, bytesRx: number, bytesTx: number, enabled: boolean, createdAt: string, updatedAt: string, connectionStatus: VpnPeerConnectionStatus, };
