// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recorte do `device` que as telas de VPN leem da linha do peer.
 *
 * O corpo em runtime é o `devices::present` inteiro — este struct **não** é
 * serializado, existe só para dar nome ao que a tabela de dispositivos VPN
 * consome. Descrever menos campos do que a resposta traz é seguro (o
 * TypeScript é estrutural); descrever campos que não existem não seria, e é
 * justamente isso que o tipo redigitado à mão arriscava.
 */
export type VpnPeerDeviceView = {
  id: number
  name: string
  ipAddress: string | null
  snmpEnabled: boolean
  status: string
}
