// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VpnPeerConnectionStatus } from "./VpnPeerConnectionStatus";

export type VpnPeerResponse = { id: number, vpnServerId: number, deviceId: number, publicKey: string, deviceProfile: string, persistentKeepalive: number, lastHandshakeAt: string | null, 
/**
 * Último keepalive contabilizado — é o sinal de vida que sustenta o status.
 */
lastSeenAt: string | null, bytesRx: number, bytesTx: number, enabled: boolean, createdAt: string, updatedAt: string, connectionStatus: VpnPeerConnectionStatus, };
