// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de `DELETE /api/vpn/peers/:id`.
 */
export type VpnPeerRevokedResponse = { message: string }
