// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VpnPeerConnectionStatus } from "./VpnPeerConnectionStatus";
import type { VpnPeerDeviceView } from "./VpnPeerDeviceView";

/**
 * Linha de `GET /api/vpn/peers`: o peer, os avisos de diagnóstico e o
 * dispositivo, achatados num objeto só — que é como a tela sempre leu.
 */
export type VpnPeerListItem = { 
/**
 * `null` quando o dispositivo do peer já foi removido — a linha continua
 * aparecendo para que o operador consiga revogá-la.
 */
device: VpnPeerDeviceView | null, id: number, vpnServerId: number, deviceId: number, publicKey: string, deviceProfile: string, persistentKeepalive: number, lastHandshakeAt: string | null, 
/**
 * Último keepalive contabilizado — é o sinal de vida que sustenta o status.
 */
lastSeenAt: string | null, bytesRx: number, bytesTx: number, enabled: boolean, createdAt: string, updatedAt: string, connectionStatus: VpnPeerConnectionStatus, 
/**
 * Túnel ativo, mas o ping falha: provável firewall bloqueando na interface WG.
 */
needsFirewallHint: boolean, 
/**
 * Túnel ativo e ping falhando, mas o monitor **não** roda no `vpn-probe` —
 * e o túnel está em outro namespace de rede. O ICMP sai da máquina da API,
 * que não tem rota para dentro do túnel: o pacote nem chega ao
 * equipamento, e acusar o firewall dele seria diagnóstico falso.
 *
 * Nunca é `true` quando o WireGuard sobe junto com a API (o padrão): ali a
 * `wg0` é do próprio processo, o pacote entra no túnel, e quem falha em
 * responder é mesmo o equipamento.
 */
pingOutsideTunnel: boolean, 
/**
 * Monitor de ping provisionado automaticamente para o peer — usado para
 * navegar ao histórico de conectividade.
 */
pingMonitorId: number | null, };
