// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerializedVpnArtifact } from './SerializedVpnArtifact'
import type { VpnPeerDeviceView } from './VpnPeerDeviceView'
import type { VpnPeerResponse } from './VpnPeerResponse'

/**
 * Resposta de `POST /api/vpn/peers`.
 */
export type VpnPeerCreatedResponse = {
  peer: VpnPeerResponse
  device: VpnPeerDeviceView | null
  artifact: SerializedVpnArtifact
}
