// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de `GET /api/vpn/peers/:id/qrcode`.
 */
export type VpnQrCodeResponse = { profile: string, fileName: string, svg: string, };
