// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VpnServerResponse = { id: number, networkId: number, interfaceName: string, listenPort: number, publicEndpoint: string | null, publicKey: string, allowPeerToPeer: boolean, mtu: number, dnsServers: string | null, active: boolean, lastSyncedAt: string | null, createdAt: string, updatedAt: string, };
