// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileCard } from './ProfileCard'
import type { VpnServerResponse } from './VpnServerResponse'

/**
 * Corpo de `GET /api/vpn/server` — o painel inteiro numa requisição.
 */
export type VpnServerStateResponse = {
  configured: boolean
  server: VpnServerResponse | null
  cidr: string | null
  serverAddress: string | null
  peersTotal: number
  peersConnected: number
  bytesRx: number
  bytesTx: number
  persistentKeepalive: number
  profiles: Array<ProfileCard>
}
