//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "alert_rules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub site_id: Option<i64>,
    pub device_id: Option<i64>,
    pub monitor_id: Option<i64>,
    pub name: String,
    pub r#type: String,
    pub template_key: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub condition: Json,
    pub severity: String,
    pub duration_seconds: i32,
    pub recovery_window_seconds: i32,
    pub flap_threshold: i32,
    pub flap_window_seconds: i32,
    pub enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alert_events::Entity")]
    AlertEvents,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::monitors::Entity",
        from = "Column::MonitorId",
        to = "super::monitors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Monitors,
    #[sea_orm(
        belongs_to = "super::sites::Entity",
        from = "Column::SiteId",
        to = "super::sites::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sites,
}

impl Related<super::alert_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertEvents.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}

impl Related<super::sites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sites.def()
    }
}
