//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "alert_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub alert_rule_id: Option<i64>,
    pub device_id: Option<i64>,
    pub monitor_id: Option<i64>,
    pub scope_key: Option<String>,
    pub status: String,
    pub severity: String,
    pub started_at: DateTimeWithTimeZone,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub data: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alert_rules::Entity",
        from = "Column::AlertRuleId",
        to = "super::alert_rules::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AlertRules,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::monitors::Entity",
        from = "Column::MonitorId",
        to = "super::monitors::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Monitors,
}

impl Related<super::alert_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertRules.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}
