//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "container_metrics_1m")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub host_key: String,
    pub container_name: String,
    pub project: Option<String>,
    pub bucket_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Double")]
    pub cpu_avg: f64,
    #[sea_orm(column_type = "Double")]
    pub cpu_max: f64,
    #[sea_orm(column_type = "Double")]
    pub memory_avg: f64,
    pub memory_max: i64,
    pub net_rx_bytes: i64,
    pub net_tx_bytes: i64,
    pub block_read_bytes: i64,
    pub block_write_bytes: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
