//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "database_connections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub engine: String,
    pub host: String,
    pub port: i32,
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_encrypted: String,
    pub ssl_mode: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub databases: Json,
    pub storage_destination_id: Option<i64>,
    pub backup_enabled: bool,
    pub backup_interval_hours: i32,
    pub backup_retention: i32,
    pub last_backup_at: Option<DateTimeWithTimeZone>,
    pub last_backup_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_backup_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::database_backups::Entity")]
    DatabaseBackups,
    #[sea_orm(
        belongs_to = "super::storage_destinations::Entity",
        from = "Column::StorageDestinationId",
        to = "super::storage_destinations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    StorageDestinations,
}

impl Related<super::database_backups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DatabaseBackups.def()
    }
}

impl Related<super::storage_destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageDestinations.def()
    }
}
