//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "database_backups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub connection_id: i64,
    pub database_name: String,
    pub storage_destination_id: Option<i64>,
    pub object_key: Option<String>,
    pub size_bytes: Option<i64>,
    pub checksum: Option<String>,
    pub tables: i32,
    pub rows: i64,
    pub duration_ms: i64,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub warnings: Json,
    pub trigger: String,
    pub started_at: DateTimeWithTimeZone,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::database_connections::Entity",
        from = "Column::ConnectionId",
        to = "super::database_connections::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DatabaseConnections,
    #[sea_orm(
        belongs_to = "super::storage_destinations::Entity",
        from = "Column::StorageDestinationId",
        to = "super::storage_destinations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    StorageDestinations,
}

impl Related<super::database_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DatabaseConnections.def()
    }
}

impl Related<super::storage_destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageDestinations.def()
    }
}
