//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub source_device_id: i64,
    pub target_device_id: i64,
    pub source_interface_id: Option<i64>,
    pub target_interface_id: Option<i64>,
    pub link_type: String,
    pub discovery_method: String,
    pub confidence: i32,
    pub confirmed: bool,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_interfaces::Entity",
        from = "Column::SourceInterfaceId",
        to = "super::device_interfaces::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DeviceInterfaces2,
    #[sea_orm(
        belongs_to = "super::device_interfaces::Entity",
        from = "Column::TargetInterfaceId",
        to = "super::device_interfaces::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DeviceInterfaces1,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::SourceDeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices2,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::TargetDeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices1,
}
