//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_credentials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "device_credentials_device_kind_unique")]
    pub device_id: i64,
    #[sea_orm(unique_key = "device_credentials_device_kind_unique")]
    pub kind: String,
    pub username: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret_encrypted: Option<String>,
    pub storage: String,
    pub port: Option<i32>,
    pub via_probe_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::probes::Entity",
        from = "Column::ViaProbeId",
        to = "super::probes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Probes,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::probes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Probes.def()
    }
}
