//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "host_metrics_1m")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub host_key: String,
    pub bucket_at: DateTimeWithTimeZone,
    pub samples: i32,
    #[sea_orm(column_type = "Double")]
    pub cpu_avg: f64,
    #[sea_orm(column_type = "Double")]
    pub cpu_max: f64,
    #[sea_orm(column_type = "Double")]
    pub memory_used_avg: f64,
    pub memory_total: i64,
    #[sea_orm(column_type = "Double")]
    pub load1: f64,
    #[sea_orm(column_type = "Double")]
    pub net_rx_bps: f64,
    #[sea_orm(column_type = "Double")]
    pub net_tx_bps: f64,
    #[sea_orm(column_type = "JsonBinary")]
    pub disks: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
