//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "metrics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub device_id: i64,
    pub interface_id: Option<i64>,
    pub monitor_id: Option<i64>,
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
    pub unit: String,
    pub recorded_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_interfaces::Entity",
        from = "Column::InterfaceId",
        to = "super::device_interfaces::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DeviceInterfaces,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::monitors::Entity",
        from = "Column::MonitorId",
        to = "super::monitors::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Monitors,
}

impl Related<super::device_interfaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceInterfaces.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}
