//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod alert_events;
pub mod alert_rules;
pub mod device_interfaces;
pub mod device_links;
pub mod devices;
pub mod discovery_results;
pub mod discovery_runs;
pub mod dns_servers;
pub mod event_outbox;
pub mod metrics;
pub mod monitor_results;
pub mod monitors;
pub mod networks;
pub mod probe_tasks;
pub mod probes;
pub mod sites;
pub mod system_settings;
pub mod users;
pub mod vpn_peers;
pub mod vpn_servers;
