//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_outbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub alert_rule_id: Option<i64>,
    pub scope_key: Option<String>,
    pub device_id: Option<i64>,
    pub group_key: String,
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub severity: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub status: String,
    pub suppress_reason: Option<String>,
    pub inhibitable: bool,
    pub deliver_after: DateTimeWithTimeZone,
    pub sent_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alert_rules::Entity",
        from = "Column::AlertRuleId",
        to = "super::alert_rules::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    AlertRules,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Devices,
}

impl Related<super::alert_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertRules.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}
