//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plugins")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub slug: String,
    pub name: String,
    pub version: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub scope: String,
    pub device_id: Option<i64>,
    pub source: String,
    pub status: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub manifest: Json,
    #[sea_orm(column_type = "Text")]
    pub script: String,
    #[sea_orm(column_type = "Text")]
    pub usage: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub compatibility: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub tests: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub review: Option<Json>,
    pub checksum: String,
    pub last_test_at: Option<DateTimeWithTimeZone>,
    pub last_test_ok: Option<bool>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(has_many = "super::plugin_runs::Entity")]
    PluginRuns,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::plugin_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginRuns.def()
    }
}
