//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "probe_tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub probe_id: i64,
    #[sea_orm(unique)]
    pub monitor_id: i64,
    pub task_id: String,
    pub r#type: String,
    pub timeout_ms: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::monitors::Entity",
        from = "Column::MonitorId",
        to = "super::monitors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Monitors,
    #[sea_orm(
        belongs_to = "super::probes::Entity",
        from = "Column::ProbeId",
        to = "super::probes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Probes,
}

impl Related<super::monitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monitors.def()
    }
}

impl Related<super::probes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Probes.def()
    }
}
