// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybookRunInput = { playbookType: string, target: string | null, deviceId: bigint | null, };
