// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybookStepResult = { stepIndex: number, stepName: string, description: string, status: string, message: string | null, data: Record<string, unknown>, };
