// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybookStepResult } from "./PlaybookStepResult";

export type PlaybookSummary = { playbookType: string, target: string | null, status: string, diagnosis: string, recommendations: Array<string>, steps: Array<PlaybookStepResult>, };
