// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeedTestProgress = { phase: string, progressPct: number, currentMbps: number | null, pingMs: number | null, jitterMs: number | null, downloadMbps: number | null, uploadMbps: number | null, serverName: string | null, serverLocation: string | null, };
