// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeedTestResult = { pingMs: number, jitterMs: number, downloadMbps: number, uploadMbps: number, serverName: string | null, serverLocation: string | null, timestamp: string, };
