// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TracerouteInput = { host: string, maxHops: number | null, timeoutMs: bigint | null, probesPerHop: number | null, };
