// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TracerouteHop = { hop: number, ip: string | null, hostname: string | null, rttMs: Array<number | null>, avgRttMs: number | null, status: string, };
