# Gerado automaticamente pelo NetMonitor — não editar manualmente.

[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = ljhm2AHgywc3Z8Js/Z932xCjPLpnH4TRFd+nUBSGeG8=
MTU = 1420
PostUp = iptables -A FORWARD -i wg0 -d 10.8.0.1 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -o wg0 -j DROP
PostDown = iptables -D FORWARD -i wg0 -d 10.8.0.1 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j DROP

# filial
[Peer]
PublicKey = YIrTl7zvBxgSxgTCHF6VsTTqz8Jy5kSjWxFkVSLUswc=
PresharedKey = IObnktthrvgdJSSC5Wb5Z36vm3NmC5FiSVrA8MNQPpA=
AllowedIPs = 10.8.0.2/32
