# Gerado automaticamente pelo NetMonitor — não editar manualmente.

[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = Gl9P/wJqzZt4L2s9XklQA2v6Mt2eH9TsUTZ0ioGpbVg=
MTU = 1420
PostUp = iptables -A FORWARD -i wg0 -d 10.8.0.1 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -o wg0 -j DROP
PostDown = iptables -D FORWARD -i wg0 -d 10.8.0.1 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j DROP

# filial
[Peer]
PublicKey = Kr/8K9PXfVd1Wl93pMXHsoYaDK0fFvEMWERJLxUvaho=
PresharedKey = 52bq13AAzSN7coN9bX7RyiXZa4IDn/TzwZGs7cEZoRw=
AllowedIPs = 10.8.0.2/32
