# Gerado automaticamente pelo NetMonitor — não editar manualmente.

[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = kE1qUUsVqZtvcqr2J+cG0IjFiFwWW/iJc/TWRQ7+rlA=
MTU = 1420
PostUp = iptables -A FORWARD -i wg0 -d 10.8.0.1 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0 -o wg0 -j DROP
PostDown = iptables -D FORWARD -i wg0 -d 10.8.0.1 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j DROP

# Peer Estado
[Peer]
PublicKey = mAlO0Se8/gzwfIYfcs2iEGq4f+/zovYLwmw636gg8jw=
PresharedKey = nB3gBFG2sBQMgUsOGAIvBadog7uw4ZiqW44p9zivC7o=
AllowedIPs = 10.8.0.2/32
